### ISSUE TITLE
强烈建议回滚 etcd 版本 3.5 -> 3.4.x

### ISSUE THREAD

**Issue by ChongmingDu** [TimeBye/kubeadm-ha#105]
**缺陷描述**

https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ?pli=1

已知大部分公有云最新托管 k8s 采用 ectd 还是3.4.x

**预期结果**

3.5.0 -> 3.4.18

**Comment by TimeBye** [comment]
<img width="1752" alt="image" src="https://user-images.githubusercontent.com/22651579/172318373-b4ca29ae-517d-4650-af2d-d9ca149402c8.png">

要不我升级到  3.5.4 去？怕影响到之前的Etcd

**Comment by TimeBye** [comment]
已更新

fdc5d34ca35283225296bbf62fc934a6be879c34
