### ISSUE TITLE
离线安装模式下安装k8s 1.21.4 + flannel + docker的组合下，cni plugin没有安装，网络故障，节点NotReady状态。

### ISSUE THREAD

**Issue by Taoup** [TimeBye/kubeadm-ha#107]
节点状态：
![image-20220530143141445](https://user-images.githubusercontent.com/22348542/171113175-91a6006d-936e-4d5c-b0a2-be7ba79c2737.png)

查看节点kubelet日志：
![image-20220530143612411](https://user-images.githubusercontent.com/22348542/171113295-b02abcde-a94e-482c-b2eb-3058202da0f9.png)

查看了下生成的flannel配置，和原本的flannel配置，发现生成的配置和原本的[配置](https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml)相比少了下面这一节：

![image](https://user-images.githubusercontent.com/22348542/171113549-e57c3c59-537f-4a3a-9c01-ab2fb88dfaf8.png)

看起来这个像是根因，不知道是不是作者有意去除这节配置的？

目前我只能通过手动去下载cni plugin然后放到节点相应目录下，来让节点回到Ready状态，请问下作者有没有更好地办法？

**Comment by TimeBye** [comment]
这里安装并没有进行修改，默认安装版本为  0.14.0，配置文件为：

https://github.com/flannel-io/flannel/blob/v0.14.0/Documentation/kube-flannel.yml

这里我也再测试一下，貌似并没有遇到过这个问题

**Comment by TimeBye** [comment]
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/22651579/172554340-aa56d3c8-6c19-40b5-854d-17dd3e6db516.png">


我本地做测试，没有复现，请问有什么其他线索吗

**Comment by Taoup** [comment]
找到进一步的原因了，貌似在第三步安装k8s组件的时候其实cni-plugins的包已经下载好，正常情况下会解压安装到/opt/cni/bin目录下，我在本机虚拟机上运行的时候就安装好了。但是在另一套环境上虽然cni-plugins下载好了，但是并没有安装上去，应该是那套环境出了什么问题。  

![image](https://user-images.githubusercontent.com/22348542/172972049-70a4a586-67d4-4215-96a7-29d428ac9bd3.png)

![image](https://user-images.githubusercontent.com/22348542/172972921-cc288335-c1ff-48bb-a9d5-f9eee7c1030f.png)

我在那套环境上使用apt命令直接安装了下kubernetes-cni这个包，还是没有把相应的插件打包到/opt/cni/bin目录。只有用dpkg命令安装才安装好。

实在是没头绪那个环境可能出了啥问题。

**Comment by Taoup** [comment]
大概是找到问题根因了，那个环境多次安装、卸载k8s，大概是kubernetes-cni没有卸载干净，导致再次安装的时候apt认为kubernetes-cni已经安装了，所以出现的问题。
