### ISSUE TITLE
release-1.20分支的离线部署中缺少两个镜像

### ISSUE THREAD

**Issue by thyme-official** [TimeBye/kubeadm-ha#111]
**缺陷描述**

在分支release-1.20中的离线部署中缺少了两个镜像，
registry.custom.local:12480/kubeadm-ha/ingress-nginx_controller:v0.47.0
registry.custom.local:12480/kubeadm-ha/metrics-server_metrics-server:v0.5.0

**Comment by TimeBye** [comment]
你好，分支release-1.20中使用的是这两个镜像

https://github.com/TimeBye/kubeadm-ha/blob/release-1.20/offline/download-images-to-registry.sh#L32-L33

**Comment by TimeBye** [comment]
感谢反馈，已修复完毕

**Comment by thyme-official** [comment]
关闭
