### ISSUE TITLE
节点更换ip

### ISSUE THREAD

**Issue by purgeyao** [TimeBye/kubeadm-ha#116]
使用kubeadm-ha部署的完整k8s集群，期间一个Worker节点所在的ip发生变更，
是自动更换ip，还是需要手动更换ip，如手动更换，需要注意什么呢

**Comment by TimeBye** [comment]
worker节点更换IP，可采用移除该节点后重新添加进集群的操作

1、 移除该节点
```
kubectl delete node xxxxx
```

2、重置该节点并重启
```
# 登录被移除的节点
kubeadm reset -f

reboot -f
```

3、[使用新IP添加该节点](https://github.com/TimeBye/kubeadm-ha/blob/master/docs/02/%E6%B7%BB%E5%8A%A0%20worker%20%E8%8A%82%E7%82%B9.md)

**Comment by purgeyao** [comment]
感谢，不过在你回复之前，我用了
1.修改所有节点vi /etc/hosts 下的变更的worker节点ip 为新的ip  重启服务器或者更新hosts 生效
2.在master 上 将ip变更的worker 踢出
3.修改hosts.s-master.hostname.ini  按照正常的添加节点流程执行
4.ansible-playbook -i example/hosts.s-master.hostname.ini -e @example/variables.yaml 81-add-worker.yml
5.重启修改后的worker

这样会有什么问题么

**Comment by TimeBye** [comment]
没什么问题，效果一样的
