### ISSUE TITLE
请问从哪个版本开始支持 Kylin V10的？

### ISSUE THREAD

**Issue by chinaboy007** [TimeBye/kubeadm-ha#118]
请问从哪个版本开始支持 Kylin V10的？ x86和arm都支持吗？ 离线包支持吗？准备用kubeadm-ha做私有化交付，感谢！

**Comment by chinaboy007** [comment]
???

**Comment by chinaboy007** [comment]
[1.22适配Anolis和Kylin](https://github.com/TimeBye/kubeadm-ha/commit/d11bda3f50bea467a814341164e49c3709cb42b2) 找到了。 强烈建议，建个群，不然问半天没人回复

**Comment by chinaboy007** [comment]
TASK [prepare/base : 加载 nf_conntrack_ipv4] *************************************************************************************************************************************************************************************************
fatal: [192.168.227.134]: FAILED! => {"changed": false, "msg": "modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.19.90-24.4.v2101.ky10.x86_64\n", "name": "nf_conntrack_ipv4", "params": "", "rc": 1, "state": "present", "stderr": "modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.19.90-24.4.v2101.ky10.x86_64\n", "stderr_lines": ["modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.19.90-24.4.v2101.ky10.x86_64"], "stdout": "", "stdout_lines": []}
...ignoring

**Comment by chinaboy007** [comment]
TASK [prepare/base : 安装基础软件包] **************************************************************************************************************************************************************************************************************
fatal: [192.168.227.134]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem 1: installed package nmap-2:7.80-1.ky10.x86_64 obsoletes nmap-ncat provided by nmap-ncat-2:6.40-19.el7.x86_64\n  - cannot install the best candidate for the job\n  - problem with installed package nmap-2:7.80-1.ky10.x86_64\n Problem 2: installed package thin-provisioning-tools-0.9.0-2.p01.ky10.x86_64 obsoletes device-mapper-persistent-data provided by device-mapper-persistent-data-0.8.5-3.el7_9.2.x86_64\n  - cannot install the best candidate for the job\n  - problem with installed package thin-provisioning-tools-0.9.0-2.p01.ky10.x86_64\n Problem 3: package socat-1.7.3.2-2.el7.x86_64 requires libreadline.so.6()(64bit), but none of the providers can be installed\n  - cannot install both readline-6.2-11.el7.x86_64 and readline-8.0-3.ky10.x86_64\n  - package NetworkManager-1:1.26.2-4.ky10.x86_64 requires libreadline.so.8()(64bit), but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package NetworkManager-1:1.26.2-4.ky10.x86_64\n Problem 4: package iscsi-initiator-utils-6.2.0.874-22.el7_9.x86_64 requires libcrypto.so.10()(64bit), but none of the providers can be installed\n  - package iscsi-initiator-utils-6.2.0.874-22.el7_9.x86_64 requires libcrypto.so.10(libcrypto.so.10)(64bit), but none of the providers can be installed\n  - cannot install both openssl-libs-1:1.0.2k-25.el7_9.x86_64 and openssl-libs-1:1.1.1f-4.p01.ky10.x86_64\n  - package OpenIPMI-2.0.29-1.ky10.x86_64 requires libcrypto.so.1.1()(64bit), but none of the providers can be installed\n  - package OpenIPMI-2.0.29-1.ky10.x86_64 requires libcrypto.so.1.1(OPENSSL_1_1_0)(64bit), but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package OpenIPMI-2.0.29-1.ky10.x86_64", "rc": 1, "results": []}

**Comment by chinaboy007** [comment]
x86_64 和 arm64经测试都有很多问题，看来只能自己制作镜像了

**Comment by TimeBye** [comment]
kylin v10 离线已添加，可以帮忙测试一下吗？

**Comment by TimeBye** [comment]
https://github.com/TimeBye/kubeadm-ha/issues/131#issue-1662014437
