### ISSUE TITLE
自己制作ARM 麒麟V10 K8S1.22.10镜像安装报错

### ISSUE THREAD

**Issue by chinaboy007** [TimeBye/kubeadm-ha#121]
自己制作ARM 麒麟V10 K8S1.22.10镜像安装报错，提示找不到repomd.xml, 请问是哪里出了问题？

TASK [prepare/base : 安装基础软件包] **************************************************************************************************************************************************************************************************************
fatal: [10.52.13.105]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'base': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}

NO MORE HOSTS LEFT *************************************************************************************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
10.52.13.105               : ok=50   changed=18   unreachable=0    failed=1    skipped=10   rescued=0    ignored=2

**Comment by Jaywoods2** [comment]
@chinaboy007 请问有指定麒麟yum源吗
```
# example/variables.yaml
base_yum_repo: https://update.cs2c.com.cn/NS/V10/V10SP2/os/adv/lic/base/$basearch/
epel_yum_repo: https://mirrors.aliyun.com/epel/8/Everything/$basearch
docker_yum_repo: https://mirrors.aliyun.com/docker-ce/linux/centos/8/$basearch/stable
```

**Comment by chinaboy007** [comment]
> 

我之前指定的centos 7的源，难道要换成centos8的源？

**Comment by Jaywoods2** [comment]
我是用8的源验证通过的

**Comment by chinaboy007** [comment]
> 我是用8的源验证通过的

我是离线安装，不可能指定外网的yum 源。
我现在就是想修改下download-yum.sh  重新制作离线包，请问麒麟的download-yum.sh 在哪下载

**Comment by Taoup** [comment]
> > 我是用8的源验证通过的
> 
> 我是离线安装，不可能指定外网的yum 源。 我现在就是想修改下download-yum.sh 重新制作离线包，请问麒麟的download-yum.sh 在哪下载

请问下你制作成功了吗

**Comment by chinaboy007** [comment]
> > > 我是用8的源验证通过的
> > 
> > 
> > 我是离线安装，不可能指定外网的yum 源。 我现在就是想修改下download-yum.sh 重新制作离线包，请问麒麟的download-yum.sh 在哪下载
> 
> 请问下你制作成功了吗

https://github.com/TimeBye/kubeadm-ha/blob/master/offline/download-yum.sh      没有成功，我之前用的是7的源，改天试试8的源

**Comment by TimeBye** [comment]
kylin v10 离线已添加，可以帮忙测试一下吗？

**Comment by TimeBye** [comment]
https://github.com/TimeBye/kubeadm-ha/issues/131#issue-1662014437
