### ISSUE TITLE
单master安装 到nginx做负载的时候失败

### ISSUE THREAD

**Issue by wakesunshine** [TimeBye/kubeadm-ha#129]
![dfa54da3ac12ee85da26eae05843995](https://user-images.githubusercontent.com/73566060/222137519-2a825c10-4880-4a44-a82e-44a5d0aa95be.png)

**Comment by wakesunshine** [comment]
[root@localhost kubeadm-ha]# grep -E -v "^$|;"  example/hosts.s-master.hostname.ini 
[all]
master01 ansible_host=10.0.1.231 ansible_port=22 ansible_user="root" ansible_ssh_pass="123"
node1 ansible_host=10.0.1.232 ansible_port=22 ansible_user="root" ansible_ssh_pass="123"
node2 ansible_host=10.0.1.233 ansible_port=22 ansible_user="root" ansible_ssh_pass="123"
[lb]
[etcd]
master01
[kube-master]
master01
[kube-worker]
master01
node1
node2
[new-master]
[new-worker]
[new-etcd]
[del-worker]
[del-master]
[del-etcd]
[del-node]
[all:vars]
skip_verify_node=false
kube_version="1.19.9"
container_manager="docker"
lb_mode="nginx"
#lb_kube_apiserver_ip="10.0.1.231"
lb_kube_apiserver_port="8443"
kube_pod_subnet="192.168.0.0/18"
kube_service_subnet="192.168.64.0/18"
kube_network_node_prefix="24"
kube_max_pods="110"
network_plugin="calico"
kubelet_root_dir="/var/lib/kubelet"
docker_storage_dir="/var/lib/docker"
containerd_storage_dir="/var/lib/containerd"
etcd_data_dir="/var/lib/etcd"

**Comment by liujiabaoaa** [comment]
怎么解决了？我也遇到这个问题了
