### ISSUE TITLE
请教下 node节点资源预留 问题

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#13]
kubeadm  node节点做 资源预留
kubelet 启动  报错：Dec 16 19:29:15 k8s-master01 kubelet[2960]: F1216 19:29:15.930514    2960 kubelet.go:1372] Failed to start ContainerManager Failed to enforce System Reserved Cgroup Limits on "/system.slice": ["system.slice"] cgroup does not exist

手工建了 system.slice 也不行

**Comment by li-sen** [comment]
kubeReservedCgroup: /system.slice/kubelet.service
kubeReserved: {'cpu':'200m','memory':'200Mi','ephemeral-storage':'10Gi'}
systemReservedCgroup: /system.slice
systemReserved: {'cpu':'200m','memory':'200Mi','ephemeral-storage':'10Gi'}

**Comment by li-sen** [comment]
[root@k8s-master01 kubelet]# find /sys/fs/cgroup -name "system.slice"
/sys/fs/cgroup/perf_event/systemd/system.slice
/sys/fs/cgroup/perf_event/system.slice
/sys/fs/cgroup/cpuset/systemd/system.slice
/sys/fs/cgroup/cpuset/system.slice
/sys/fs/cgroup/pids/systemd/system.slice
/sys/fs/cgroup/pids/system.slice
/sys/fs/cgroup/freezer/systemd/system.slice
/sys/fs/cgroup/freezer/system.slice
/sys/fs/cgroup/hugetlb/systemd/system.slice
/sys/fs/cgroup/hugetlb/system.slice
/sys/fs/cgroup/cpu,cpuacct/systemd/system.slice
/sys/fs/cgroup/cpu,cpuacct/system.slice
/sys/fs/cgroup/devices/systemd/system.slice
/sys/fs/cgroup/devices/system.slice
/sys/fs/cgroup/memory/systemd/system.slice
/sys/fs/cgroup/memory/system.slice
/sys/fs/cgroup/blkio/systemd/system.slice
/sys/fs/cgroup/blkio/system.slice
/sys/fs/cgroup/net_cls,net_prio/systemd/system.slice
/sys/fs/cgroup/net_cls,net_prio/system.slice
/sys/fs/cgroup/systemd/systemd/system.slice
/sys/fs/cgroup/systemd/system.slice
[root@k8s-master01 kubelet]#

**Comment by TimeBye** [comment]
@li-sen 你好，系统组件资源预留以及kubernetes组件资源预留相关配置还在测试中，近期将合并到主分支中。

临时解决办法如下：

- 编辑 `/var/lib/kubelet/config.yaml` 文件
- 添加以下内容（预留值视实际情况修改）
  ```diff
    ...
    evictionHard:
      imagefs.available: 15%
      memory.available: 100Mi
      nodefs.available: 10%
      nodefs.inodesFree: 5%
  + kubeReserved:
  +   cpu: "500m"
  +   memory: "1Gi"
  + systemReserved:
  +   cpu: "1"
  +   memory: "1Gi"
  +   ephemeral-storage: "10Gi"
    ...
  ```
- 重启该节点 kubelet：`systemctl resart kubelet`

**Comment by TimeBye** [comment]
@li-sen  Hi，资源预留设置已合并到主分支，欢迎使用，多多交流。

- 示例：
```ini
[all]
node1 ansible_host=192.168.56.11 ansible_port=22 ansible_user="vagrant" ansible_ssh_pass="vagrant" system_cpu_reserved="400m" system_memory_reserved="1024Mi" system_ephemeral_storage_reserved="14Gi"
node2 ansible_host=192.168.56.12 ansible_port=22 ansible_user="vagrant" ansible_ssh_pass="vagrant" system_cpu_reserved="600m" system_memory_reserved="2048Mi" system_ephemeral_storage_reserved="16Gi"
node3 ansible_host=192.168.56.13 ansible_port=22 ansible_user="vagrant" ansible_ssh_pass="vagrant" system_cpu_reserved="800m" system_memory_reserved="3072Mi" system_ephemeral_storage_reserved="18Gi"

[lb]

[etcd]
node1
node2
node3

[kube-master]
node1
node2
node3

[kube-worker]
node1
node2
node3

[new-master]

[new-worker]

[new-etcd]

[all:vars]
skip_verify_node=false

system_reserved_enabled=true

kube_version="1.17.0"
lb_mode="haproxy"
lb_kube_apiserver_port="8443"
kube_pod_subnet="10.244.0.0/18"
kube_service_subnet="10.244.64.0/18"
network_plugin="kube-ovn"
kubelet_root_dir="/var/lib/kubelet"
docker_storage_dir="/var/lib/docker"
etcd_data_dir="/var/lib/etcd"
```

**Comment by li-sen** [comment]
本地测过？

**Comment by li-sen** [comment]
垃圾回收 或者说 资源回收这方面貌似也没做嘛

**Comment by li-sen** [comment]
你这个 有在生产上跑？？

**Comment by TimeBye** [comment]
资源回收是有做配置的哦，只是当前还没有将其作为可配置项。
https://github.com/TimeBye/kubeadm-ha/blob/master/roles/kube-worker/templates/kubelet-config.v1beta1.yaml.j2#L57-L58

计划后期将 kubelet、kube-proxy 的可配置项用 group_vars 进行实现。

PS：
1. 合并到master分支的脚本肯定会在本地和阿里云上做测试的
1. 现猪齿鱼的正式环境k8s就是本项目搭建的
