### ISSUE TITLE
kylin v10 x86 安装k8s 1.22 报错

### ISSUE THREAD

**Issue by chinaboy007** [TimeBye/kubeadm-ha#131]
**缺陷描述**

**kylin v10 x86 安装k8s 1.22 报错**

TASK [prepare/base : 添加 epel 仓库] ***********************************************************************************************************************************************************************************************************
fatal: [192.168.227.130]: FAILED! => {"msg": "An unhandled exception occurred while templating '{%- if ansible_distribution_major_version is version('8', '<') -%} http://mirrors.aliyun.com/epel/$releasever/$basearch {%- else -%} https://mirrors.aliyun.com/epel/$releasever/Everything/$basearch {%- endif -%}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Version comparison: '<' not supported between instances of 'str' and 'int'"}

**Comment by chinaboy007** [comment]
补充一下，在线安装正常，离线安装不行，很多依赖包没有打包进去

**Comment by TimeBye** [comment]
kylin v10 离线已添加，可以帮忙测试一下吗？
