### ISSUE TITLE
1.25.5初始化集群报错

### ISSUE THREAD

**Issue by 1561630125** [TimeBye/kubeadm-ha#132]
**缺陷描述**
1.25.5初始化集群报错

**如何复现**

复现的步骤：

1. 第一步：编写 inventory.ini 文件，内容如下
container_manager="docker"

2. 第二步：编写 variables.yaml 文件，内容如下

3. 第三步：执行部署命令，命令如下
ansible-playbook -i example/hosts.m-master.ip.ini 90-init-cluster.yml

4. 出现错误

![image](https://github.com/TimeBye/kubeadm-ha/assets/18327163/403d3d8d-c833-428c-85a3-8f97814be7ed)

**Comment by TimeBye** [comment]
已更新 containerd 解决此问题
