### ISSUE TITLE
[Bug]K8s集群满一年后，Apiserver日志报证书过期，导致该master节点不可用。

### ISSUE THREAD

**Issue by wduan123** [TimeBye/kubeadm-ha#133]
**缺陷描述**

K8s集群满一年后，Apiserver 日志报证书过期，导致该 master 节点不可用。
但是用 openssl 命令查看证书，有效期都是99年。

我又新建了一个集群，手动修改服务器时间（1年后），Apiserver 也开始报证书过期的错误。

**预期结果**

K8s 集群能正常使用。

**截图信息**
- Apiserver 错误日志：
![image](https://github.com/TimeBye/kubeadm-ha/assets/93708226/3c61ac74-4fa0-4912-81d8-afa07ccbc93b)

- 集群节点信息：
![image](https://github.com/TimeBye/kubeadm-ha/assets/93708226/0d6a87c5-0e98-4a7f-881d-54b46707ad4c)

- 命令查看 K8s 证书过期时间：
![image](https://github.com/TimeBye/kubeadm-ha/assets/93708226/bf49c687-2a41-4044-8f40-430650bef453)

**Comment by wanghe-fit2cloud** [comment]
@TimeBye

**Comment by TimeBye** [comment]
你好，还有现场吗？开远程看一看

**Comment by wduan123** [comment]
> 你好，还有现场吗？开远程看一看

可以手动修改服务器时间，必现上述问题。

**Comment by TimeBye** [comment]
直接修改时间肯定会出现的，因为kubelet反应不过来需要续签证书，可在用户使用较少的时候重启一下kubelet看是否会续签，受影响时间应该在5分钟以内。

```
systemctl restart kubelet
```

**Comment by wduan123** [comment]
> 直接修改时间肯定会出现的，因为kubelet反应不过来需要续签证书，可在用户使用较少的时候重启一下kubelet看是否会续签，受影响时间应该在5分钟以内。
> 
> ```
> systemctl restart kubelet
> ```

是的，手动重启过 kubelet 等服务，没有生效。
目前只能是手动重启 master 节点，这就有点儿奇怪，真不是到是哪里的问题。

**Comment by TimeBye** [comment]
不然就是 `kube-controller-manager` 办法证书的时候出错了，可以看看 `kube-controller-manager` 的日志排查一下，然后重启 `kube-controller-manager`。

重启方式：
```
# 在 metadata.labels 中任意增加一个键值对
vi /etc/kubernetes/manifests/kube-controller-manager.yaml
```
