### ISSUE TITLE
K8S Node节点重新初始化安装

### ISSUE THREAD

**Issue by liujiabaoaa** [TimeBye/kubeadm-ha#135]
问题1
一个K8S的Node节点 被别人安装了一些我未知的组件，然后重启了Node节点服务器，导致Node节点在K8S集群中是Noready状态。
我排查发现 nginx的插件也未启动状态，kubelet的驱动也是cgroupfs，而不是systemd。

需求：
我现在想对这台Node节点上面的K8S相关的组件进行初始化重新安装，而不影响master正常的运行，同时还保障Node节点上面非K8S组件相关的数据安全 不丢失。 我看了ansible的脚本，是使用 添加 worker 节点.md 的步骤吗？

问题2
我安装的过程中出现如下报错
安装命令
ansible-playbook -i example/hosts.allinone.hostname.ini 90-init-cluster.yml 

安装报错的日志文件如下：
![image](https://github.com/TimeBye/kubeadm-ha/assets/26737572/d645b8ac-9cdb-4bf9-b407-7f0fb2410283)

[a.log](https://github.com/TimeBye/kubeadm-ha/files/12237038/a.log)

非常感谢 维护者的解答，先谢谢了。

**Comment by liujiabaoaa** [comment]
主机IP 的配置文件附件如下
[hosts.allinone.hostname.txt](https://github.com/TimeBye/kubeadm-ha/files/12237071/hosts.allinone.hostname.txt)

**Comment by TimeBye** [comment]
你好，每个节点重启下containerd就好了

```
systemctl restart containerd
```

**Comment by TimeBye** [comment]
你好，还有现场吗？可以远程看看吗

**Comment by liujiabaoaa** [comment]
感谢回复，问题已解决。问题大概是这样的。我拉取了master的分支的代码，然后hosts.allinone.hostname.txt里面填写了  kube_version="1.22.4"  报错这个了。   我最后拉取了对应的1.22版本的分支代码，，最后安装 就没有报错了。

**Comment by TimeBye** [comment]
好的 解决了就好
