### ISSUE TITLE
什么时候可以支持anolis8 版本，我本地用离线包部署安装失败

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#137]
[root@lisen-deploy ~]# cat /etc/os-release
NAME="Anolis OS"
VERSION="8.8"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.8"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.8"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

[root@lisen-deploy ~]#

**Comment by TimeBye** [comment]
cpu 是什么架构？需要那个kubernetes版本？可以先临时生成一个

**Comment by li-sen** [comment]
普通x86，k8s 就 1.27.4 也行，我自己试了下失败好几次。

**Comment by TimeBye** [comment]
已支持，请查看离线安装文档
