### ISSUE TITLE
 OpenEuler 

### ISSUE THREAD

**Issue by EasonHe** [TimeBye/kubeadm-ha#138]
OpenEuler  操作系统支持的21 还是22 的，有明确验证的版本么

**Comment by TimeBye** [comment]
测试以下镜像，没有问题，你在安装时遇到什么问题了吗
镜像：openEuler-22.03-LTS-SP2-x86_64-dvd.iso


![image](https://github.com/TimeBye/kubeadm-ha/assets/22651579/79f7e31e-3599-4a5e-9e0a-e054f50f26d7)

**Comment by TimeBye** [comment]
镜像：openEuler-23.03-x86_64-dvd.iso

![image](https://github.com/TimeBye/kubeadm-ha/assets/22651579/8f9e83f0-9650-42c9-a208-f313ee158908)

**Comment by TimeBye** [comment]
镜像：openEuler-21.09-x86_64-dvd.iso

```
sed -i 's repo.openeuler.org archives.openeuler.openatom.cn g' /etc/yum.repos.d/openEuler.repo
```

![image](https://github.com/TimeBye/kubeadm-ha/assets/22651579/ecd352e2-cf92-4fce-83e8-0ddde404d1b5)
