### ISSUE TITLE
镜像拉取失败——registry.aliyuncs.com/kubeadm-ha/pause:3.9

### ISSUE THREAD

**Issue by changeflyhigh** [TimeBye/kubeadm-ha#144]
**缺陷描述**

 registry.aliyuncs.com/kubeadm-ha/pause:3.9
镜像拉取失败

# crictl pull registry.aliyuncs.com/kubeadm-ha/pause:3.9

[root@node2 ~] {17:01:38} (1)
# crictl images
IMAGE                                    TAG                 IMAGE ID            SIZE
registry.aliyuncs.com/kubeadm-ha/nginx   1.25-alpine         01e5c69afaf63       18MB
registry.aliyuncs.com/kubeadm-ha/pause   3.0                 5fbdc14c118c3       313kB

清晰而简明的描述缺陷是什么。
 registry.aliyuncs.com/kubeadm-ha/pause:3.9
镜像拉取失败

**环境 (请填写以下信息):**

执行下面括号中的命令，提交返回结果

- **OS** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
Linux 5.4.92-1.el7.elrepo.x86_64 x86_64
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Ansible版本** (`ansible --version`):
/usr/local/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.exceptions import InvalidSignature
ansible 2.10.17
  config file = /root/kubeadm-ha-release-1.27/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 14 2023, 16:29:52) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

- **Python版本** (`python --version`):
Python 2.7.5
- **Kubeadm-ha版本(commit)** (`git rev-parse --short HEAD`):
release-1.27

**如何复现**

复现的步骤：
    ```
crictl pull registry.aliyuncs.com/kubeadm-ha/pause:3.9
    ```

4. 出现错误
    ```
    E1207 17:01:38.404862    6157 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.aliyuncs.com/kubeadm-ha/pause:3.9\": failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:e6f1816883972d4be47bd48879a08919b96afcd344132622e4d444987919323c (application/vnd.docker.container.image.v1+json) from remote: not found" image="registry.aliyuncs.com/kubeadm-ha/pause:3.9"
FATA[0001] pulling image: rpc error: code = NotFound desc = failed to pull and unpack image "registry.aliyuncs.com/kubeadm-ha/pause:3.9": failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:e6f1816883972d4be47bd48879a08919b96afcd344132622e4d444987919323c (application/vnd.docker.container.image.v1+json) from remote: not found 
    ```

**预期结果**

能正常拉取镜像  registry.aliyuncs.com/kubeadm-ha/pause:3.9

**![图片](https://github.com/TimeBye/kubeadm-ha/assets/30860085/914b67e3-ac78-4e74-8f61-8f332fef6d09)**

如果可以的话，添加屏幕截图来帮助解释你的问题。

**其他事项**

在此处添加有关该问题的任何其他事项。

**Comment by TimeBye** [comment]
阿里云杭州区容器镜像服务的问题，请等待修复

**Comment by TimeBye** [comment]
已可正常拉取镜像
