### ISSUE TITLE
Add install the netaddr

### ISSUE THREAD

**Issue by Nedved-liao** [TimeBye/kubeadm-ha#15]
Feature Request:
When I run to generate a certificate in kube-certificates/common.yml

An error is :
fatal: [192.168.1.100]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: {{ SERVICE_CIDR | ipaddr(‘net‘) | ipaddr(1) | ipaddr(‘address‘) }}: The ipaddr filter requires python-netaddr be installed on the ansible controller"}

Fix :
pip install netaddr

OS :
CentOS Linux release 7.6.1810 (Core)
The minimum installation

**Comment by TimeBye** [comment]
你好，建议ansible环境使用项目下提供的脚本进行安装

https://github.com/TimeBye/kubeadm-ha/blob/master/install-ansible.sh#L5

**Comment by TimeBye** [comment]
https://github.com/TimeBye/kubeadm-ha/blob/master/docs/01-%E9%9B%86%E7%BE%A4%E5%AE%89%E8%A3%85.md#%E5%AE%89%E8%A3%85-ansible-%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83
