### ISSUE TITLE
22-ingress-controller.yml 遇到问题

### ISSUE THREAD

**Issue by macaty** [TimeBye/kubeadm-ha#16]
[root@b1xtw22-pve-192 kubeadm-ha]# ansible-playbook -i example/hosts.m-master.ip.install.ini 22-ingress-controller.yml

PLAY [kube-master[0]] *********************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************
ok: [192.168.3.23]

TASK [plugins/ingress-controller : 在第一台 master 节点创建 ingress-controller 配置文件目录] ************************************************************************************************************
ok: [192.168.3.23]

TASK [plugins/ingress-controller : 获取当前 kubernetes 版本] ************************************************************************************************************************************
changed: [192.168.3.23]
included: /root/kubeadm-ha/roles/plugins/ingress-controller/tasks/nginx-ingress-controller.yml for 192.168.3.23

TASK [plugins/ingress-controller : 渲染 nginx-ingress-controller 配置文件] **********************************************************************************************************************
fatal: [192.168.3.23]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: Unable to look up a name or access an attribute in template string (apiVersion: v1\nkind: Namespace\nmetadata:\n  name: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\n\n---\n\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: nginx-configuration\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\ndata:\n  proxy-body-size: \"0\"\n  server-tokens: \"false\"\n  proxy-connect-timeout: \"60\"\n  # log-format-upstream: >\n  #   '{\"time\": \"$time_iso8601\", \"remote_addr\": \"$remote_addr\", \"x-forward-for\": \"$proxy_add_x_forwarded_for\",\n  #   \"the_real_ip\": \"$the_real_ip\", \"upstream_addr\": \"$upstream_addr\",\"remote_user\":\"$remote_user\",\n  #   \"bytes_sent\": $bytes_sent, \"request_time\": $request_time, \"status\":$status, \"vhost\": \"$host\", \n  #   \"request_proto\": \"$server_protocol\", \"path\": \"$uri\",\"request_query\": \"$args\",\n  #   \"request_length\": $request_length, \"duration\": $request_time,\"method\": \"$request_method\", \n  #   \"http_referrer\": \"$http_referer\", \"http_user_agent\":\"$http_user_agent\",\n  #   \"proxy_protocol_addr\":\"$proxy_protocol_addr\" }'\n  # compute-full-forwarded-for: \"true\"\n  # forwarded-for-header: X-Forwarded-For\n  # use-forwarded-headers: \"true\"\n  # enable-vts-status: \"true\"\n  # use-proxy-protocol: \"true\"\n---\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: tcp-services\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\n\n---\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: udp-services\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\n\n{% if \"PodSecurityPolicy\" in kube_apiserver_enable_admission_plugins %}\n---\napiVersion: policy/v1beta1\nkind: PodSecurityPolicy\nmetadata:\n  name: psp-nginx-ingress\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nspec:\n  allowedCapabilities:\n    - NET_BIND_SERVICE\n  privileged: false\n  allowPrivilegeEscalation: true\n  # Allow core volume types.\n  volumes:\n    - 'configMap'\n    #- 'emptyDir'\n    #- 'projected'\n    - 'secret'\n    #- 'downwardAPI'\n  hostNetwork: false\n  hostIPC: false\n  hostPID: false\n  runAsUser:\n    # Require the container to run without root privileges.\n    rule: 'MustRunAsNonRoot'\n  supplementalGroups:\n    rule: 'MustRunAs'\n    ranges:\n      # Forbid adding the root group.\n      - min: 1\n        max: 65535\n  fsGroup:\n    rule: 'MustRunAs'\n    ranges:\n      # Forbid adding the root group.\n      - min: 1\n        max: 65535\n  readOnlyRootFilesystem: false\n  seLinux:\n    rule: 'RunAsAny'\n{% endif %}\n---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: nginx-ingress-serviceaccount\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\n\n---\napiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRole\nmetadata:\n  name: nginx-ingress-clusterrole\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nrules:\n{% if \"PodSecurityPolicy\" in kube_apiserver_enable_admission_plugins %}\n  # Cluster role which grants access to the privileged pod security policy\n  - apiGroups:\n    - extensions\n    resourceNames:\n    - psp-nginx-ingress\n    resources:\n    - podsecuritypolicies\n    verbs:\n    - use\n{% endif %}\n  - apiGroups:\n      - \"\"\n    resources:\n      - configmaps\n      - endpoints\n      - nodes\n      - pods\n      - secrets\n    verbs:\n      - list\n      - watch\n  - apiGroups:\n      - \"\"\n    resources:\n      - nodes\n    verbs:\n      - get\n  - apiGroups:\n      - \"\"\n    resources:\n      - services\n    verbs:\n      - get\n      - list\n      - watch\n  - apiGroups:\n      - \"\"\n    resources:\n      - events\n    verbs:\n      - create\n      - patch\n  - apiGroups:\n      - \"extensions\"\n{% if kubeadm_version_output.stdout is version('v1.14.0', '>=') %}\n      - \"networking.k8s.io\"\n{% endif %}\n    resources:\n      - ingresses\n    verbs:\n      - get\n      - list\n      - watch\n  - apiGroups:\n      - \"extensions\"\n{% if kubeadm_version_output.stdout is version('v1.14.0', '>=') %}\n      - \"networking.k8s.io\"\n{% endif %}\n    resources:\n      - ingresses/status\n    verbs:\n      - update\n\n---\napiVersion: rbac.authorization.k8s.io/v1beta1\nkind: Role\nmetadata:\n  name: nginx-ingress-role\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nrules:\n  - apiGroups:\n      - \"\"\n    resources:\n      - configmaps\n      - pods\n      - secrets\n      - namespaces\n    verbs:\n      - get\n  - apiGroups:\n      - \"\"\n    resources:\n      - configmaps\n    resourceNames:\n      # Defaults to \"<election-id>-<ingress-class>\"\n      # Here: \"<ingress-controller-leader>-<nginx>\"\n      # This has to be adapted if you change either parameter\n      # when launching the nginx-ingress-controller.\n      - \"ingress-controller-leader-nginx\"\n    verbs:\n      - get\n      - update\n  - apiGroups:\n      - \"\"\n    resources:\n      - configmaps\n    verbs:\n      - create\n  - apiGroups:\n      - \"\"\n    resources:\n      - endpoints\n    verbs:\n      - get\n\n---\napiVersion: rbac.authorization.k8s.io/v1beta1\nkind: RoleBinding\nmetadata:\n  name: nginx-ingress-role-nisa-binding\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nroleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: Role\n  name: nginx-ingress-role\nsubjects:\n  - kind: ServiceAccount\n    name: nginx-ingress-serviceaccount\n    namespace: ingress-controller\n\n---\napiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRoleBinding\nmetadata:\n  name: nginx-ingress-clusterrole-nisa-binding\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nroleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: ClusterRole\n  name: nginx-ingress-clusterrole\nsubjects:\n  - kind: ServiceAccount\n    name: nginx-ingress-serviceaccount\n    namespace: ingress-controller\n\n---\n\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: nginx-ingress-controller\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nspec:\n  replicas: {{ INGRESS_MIN_REPLICAS }}\n  selector:\n    matchLabels:\n      app.kubernetes.io/name: ingress-nginx\n      app.kubernetes.io/part-of: ingress-nginx\n  template:\n    metadata:\n      labels:\n        app.kubernetes.io/name: ingress-nginx\n        app.kubernetes.io/part-of: ingress-nginx\n      annotations:\n        prometheus.io/port: \"10254\"\n        prometheus.io/scrape: \"true\"\n    spec:\n      # wait up to five minutes for the drain of connections\n      terminationGracePeriodSeconds: 300\n      affinity:\t\n        podAntiAffinity:\t\n          requiredDuringSchedulingIgnoredDuringExecution:\n          - labelSelector:\n              matchExpressions:\n              - key: app.kubernetes.io/name\n                operator: In\n                values:\n                - ingress-nginx\t\n            topologyKey: kubernetes.io/hostname\n      serviceAccountName: nginx-ingress-serviceaccount\n      nodeSelector:\n        beta.kubernetes.io/os: linux\n      containers:\n        - name: nginx-ingress-controller\n          image: {{ nginx_ingress_image }}\n          args:\n            - /nginx-ingress-controller\n            - --configmap=$(POD_NAMESPACE)/nginx-configuration\n            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services\n            - --udp-services-configmap=$(POD_NAMESPACE)/udp-services\n            - --publish-service=$(POD_NAMESPACE)/ingress-nginx\n            - --annotations-prefix=nginx.ingress.kubernetes.io\n          securityContext:\n            allowPrivilegeEscalation: true\n            capabilities:\n              drop:\n                - ALL\n              add:\n                - NET_BIND_SERVICE\n            # www-data -> 101\n            runAsUser: 101\n          env:\n            - name: POD_NAME\n              valueFrom:\n                fieldRef:\n                  fieldPath: metadata.name\n            - name: POD_NAMESPACE\n              valueFrom:\n                fieldRef:\n                  fieldPath: metadata.namespace\n          ports:\n            - name: http\n              containerPort: 80\n              protocol: TCP\n            - name: https\n              containerPort: 443\n              protocol: TCP\n          livenessProbe:\n            failureThreshold: 3\n            httpGet:\n              path: /healthz\n              port: 10254\n              scheme: HTTP\n            initialDelaySeconds: 10\n            periodSeconds: 10\n            successThreshold: 1\n            timeoutSeconds: 10\n          readinessProbe:\n            failureThreshold: 3\n            httpGet:\n              path: /healthz\n              port: 10254\n              scheme: HTTP\n            periodSeconds: 10\n            successThreshold: 1\n            timeoutSeconds: 10\n          lifecycle:\n            preStop:\n              exec:\n                command:\n                  - /wait-shutdown\n          resources:\n            limits:\n              cpu: 1000m\n              memory: 1Gi\n            requests:\n              cpu: 500m\n              memory: 512Mi\n---\n\napiVersion: v1\nkind: Service\nmetadata:\n  name: ingress-nginx\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nspec:\n  type: NodePort\n  externalTrafficPolicy: {{ ingress_controller_external_traffic_policy }}\n{% if kube_proxy_mode == \"iptables\" %}\n  externalIPs:\n{{ INGRESS_EXTERNALIPS }}\n{% endif %}\n  ports:\n    - name: http\n      port: 80\n      targetPort: 80\n      protocol: TCP\n      nodePort: {{ ingress_controller_http_nodeport }}\n    - name: https\n      port: 443\n      targetPort: 443\n      protocol: TCP\n      nodePort: {{ ingress_controller_https_nodeport }}\n  selector:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\n---\napiVersion: autoscaling/v2beta1\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: nginx-ingress-controller\n  namespace: ingress-controller\n  labels:\n    app.kubernetes.io/name: ingress-nginx\n    app.kubernetes.io/part-of: ingress-nginx\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: nginx-ingress-controller\n  minReplicas: {{ INGRESS_MIN_REPLICAS }}\n  maxReplicas: {{ INGRESS_MAX_REPLICAS }}\n  metrics:\n    - resource:\n        name: cpu\n        targetAverageUtilization: 60\n      type: Resource\n    - resource:\n        name: memory\n        targetAverageUtilization: 60\n      type: Resource).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'AnsibleUndefined' is not iterable"}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************
192.168.3.23               : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by TimeBye** [comment]
你好，请拉取最新master分支进行部署

**Comment by macaty** [comment]
TASK [plugins/ingress-controller : 在第一台 master 节点创建 ingress-controller 配置文件目录] *****************************************************************************
ok: [192.168.3.23]

TASK [plugins/ingress-controller : 获取当前 kubernetes 版本] *****************************************************************************************************
changed: [192.168.3.23]
included: /root/kubeadm-ha/roles/plugins/ingress-controller/tasks/nginx-ingress-controller.yml for 192.168.3.23

TASK [plugins/ingress-controller : 渲染 nginx-ingress-controller 配置文件] ***************************************************************************************
ok: [192.168.3.23]
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (24 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (23 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (22 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (21 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (20 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (19 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (18 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (17 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (16 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (15 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (14 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (13 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (12 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (11 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (10 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (9 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (8 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (7 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (6 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (5 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (4 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (3 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (2 retries left).
FAILED - RETRYING: 轮询等待 nginx-ingress-controller 运行 (1 retries left).

TASK [plugins/ingress-controller : 轮询等待 nginx-ingress-controller 运行] ***************************************************************************************
fatal: [192.168.3.23]: FAILED! => {"attempts": 24, "changed": true, "cmd": "kubectl get pod --all-namespaces -o wide | grep 'nginx-ingress' | awk '{print $4}'", "delta": "0:00:02.009526", "end": "2020-05-09 02:14:46.794684", "rc": 0, "start": "2020-05-09 02:14:44.785158", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

**Comment by macaty** [comment]
重新拉取最新的分支，还遇到这个问题。

**Comment by macaty** [comment]
手动安装了一下,就可以了。
kubectl apply -f /etc/kubernetes/plugins/ingress-controller/nginx-ingress-controller.yaml --record

**Comment by macaty** [comment]
另外咨询一下 v1.18.2，这个版本可以支持了吗？

**Comment by TimeBye** [comment]
这一步并不是报错，只是拉取镜像较慢，还没有running而已，所有带`ignoring`提示的都可以忽略。
```
TASK [plugins/ingress-controller : 轮询等待 nginx-ingress-controller 运行] ***************************************************************************************
fatal: [192.168.3.23]: FAILED! => {"attempts": 24, "changed": true, "cmd": "kubectl get pod --all-namespaces -o wide | grep 'nginx-ingress' | awk '{print $4}'", "delta": "0:00:02.009526", "end": "2020-05-09 02:14:46.794684", "rc": 0, "start": "2020-05-09 02:14:44.785158", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring
```


是支持 `v1.18.2` 的

**Comment by macaty** [comment]
谢谢。

**Comment by macaty** [comment]
你们开个讨论组呗，这个项目比收费的良心多了。
