### ISSUE TITLE
部署完成了，如何更改 docker 的配置呢？

### ISSUE THREAD

**Issue by bingoku** [TimeBye/kubeadm-ha#17]
已经部署完毕，运行都正常，想批量修改一下docker 的配置

![image](https://user-images.githubusercontent.com/4134788/81384284-04a5cd80-9144-11ea-97d2-ef88214dd6d7.png)

运行什么命令？

**Comment by TimeBye** [comment]
修改配置后执行

```
ansible-playbook -i example/hosts.m-master.ip.ini -e @example/variables.yaml 02-docker.yml
```
