### ISSUE TITLE
如何为 kubelet 新增 extra_binds 字段 呢？

### ISSUE THREAD

**Issue by bingoku** [TimeBye/kubeadm-ha#18]
想部署一个 openebs

![image](https://user-images.githubusercontent.com/4134788/81778547-a7d05b80-9525-11ea-9f9e-60ef4642eb65.png)

https://docs.openebs.io/docs/next/prerequisites.html#

**Comment by TimeBye** [comment]
由于Rancher部署的kubelet使用容器运行，故需要添加extra_binds字段。但本项目kubelet是yum或者apt-get安装，是直接在节点上运行的，故不需要添加extra_binds字段。

openebs直接使用helm进行安装即可

https://docs.openebs.io/

**Comment by TimeBye** [comment]
https://toutiao.io/posts/nmflsd/preview
