### ISSUE TITLE
针对新版 Ansible 增加额外的配置

### ISSUE THREAD

**Issue by eliu** [TimeBye/kubeadm-ha#21]
1. 新版 Ansible 要求主机操作系统下需要安装 sshpass ，否则运行失败。

建议增加针对 macOS 文档说明：
```
# https://gist.github.com/arunoda/7790979
$ brew install http://git.io/sshpass.rb
```

2. 新版 Ansible 默认会对没条命令输出 CowSay 图形提示，建议默认在 ansible.cfg 中关掉这个选项：

ansible.cfg
```
[defaults]
nocows = 1
```

**Comment by TimeBye** [comment]
你好，针对 macOS 文档说明近期我添加上去，谢谢反馈

Ansible 版本建议安装 2.8.5，不要安装新版本，新版本可能语法有所改变，脚本无法正常运行。

**Comment by TimeBye** [comment]
安装文档已更新，谢谢反馈

https://github.com/TimeBye/kubeadm-ha/blob/master/docs/01-%E9%9B%86%E7%BE%A4%E5%AE%89%E8%A3%85.md#%E5%AE%89%E8%A3%85-ansible-%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83
