### ISSUE TITLE
在使用过程中有很多的配置中kube_proxy_mode还是使用iptables的，能默认使用ipvs吗？

### ISSUE THREAD

**Issue by vperson** [TimeBye/kubeadm-ha#25]
iptables有很多的问题，很多是在使用了以后才发现使用了iptables，然后又要一批一批的去改svc改成ipvs。

**Comment by TimeBye** [comment]
我也很想把 iptables 改为 ipvs。

如果使用ipvs，但一些同事并不知道使用的是ipvs，他们会习惯性的将节点的ip写在svc的externalIPs字段中去访问pod，导致kube-proxy将节点ip作为vip进行处理，从而该节点崩溃，如果设置为master节点ip，那麻烦就更大了，可能导致整个集群无法使用。故一直沿用了iptables作为默认值。

**Comment by vperson** [comment]
好吧，但感觉直接设置externalIPs并不是一个好的暴露方式。从HA角度或者使用效率上面。
那能否把kube_proxy_mode这个变量抽象到最外面的host.ini里面这样，就可以统一修改了。

**Comment by TimeBye** [comment]
直接在hosts.ini文件中 `all:vars`域中添加即可

```
kube_proxy_mode="ipvs"
```

**Comment by vperson** [comment]
好的，谢谢
