### ISSUE TITLE
集群容易出现时间差问题，建议加上NTP、chrony或者关闭功能

### ISSUE THREAD

**Issue by vperson** [TimeBye/kubeadm-ha#26]
有些IDC机房会禁止使用NTP所以只能用chrony会比较好，但是云环境默认配置过NTP，又不喜欢配置。

可以将https://github.com/easzlab/kubeasz/tree/master/roles/chrony 的内容Copy过来。

**Comment by TimeBye** [comment]
你好，这个可以使用 DaemonSet 来解决此问题，就当是一个搭建完集群的小测试。（搭建集群前手动同步一下master节点时间也不是很麻烦的事儿）

**Comment by TimeBye** [comment]
https://github.com/geoffh1977/docker-chrony/tree/master/manifests

可以参考一下这里

**Comment by li-sen** [comment]
这个功能也属于刚需吧，建议支持，避免很多人人安装集群网络这事~

**Comment by TimeBye** [comment]
功能已实现 https://github.com/TimeBye/kubeadm-ha/commit/f1d0d6a69e8f5bb31a9f0020484a5470ba243f12
