### ISSUE TITLE
Centos8 安装失败

### ISSUE THREAD

**Issue by Cutie-Sakura** [TimeBye/kubeadm-ha#27]
PLAY [all] *********************************************************************

TASK [设置代理服务器环境变量] *************************************************************
ok: [192.168.85.131]

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [192.168.85.131]
included: /opt/k8s/git/kubeadm-ha/roles/prepare/base/tasks/verify_variables.yml for 192.168.85.131

TASK [prepare/base : 校验 NodeName 是否合法] *****************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 etcd 节点数量] *********************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 master 节点数量] *******************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 worker 节点数量] *******************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 new-etcd 节点组数量] ****************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 etcd 节点数量] *********************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 lb 模式类型] ***********************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 lb 模式端口设置] *********************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 kube-proxy 模式类型] ***************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 ingress controller node port 端口设置] *********************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 ingress controller http node port 端口设置] ****************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 ingress controller https node port 端口设置] ***************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}
included: /opt/k8s/git/kubeadm-ha/roles/prepare/base/tasks/verify_node.yml for 192.168.85.131

TASK [prepare/base : 校验节点操作系统] *************************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验节点 systemd 类型操作系统] **************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验节点系统内核] *************************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验节点系统架构] *************************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验节点系统版本] *************************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 master 节点内存] *******************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 worker 节点内存] *******************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 master 节点CPU核数] ****************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [prepare/base : 校验 worker 节点CPU核数] ****************************************
ok: [192.168.85.131] => {
    "changed": false,
    "msg": "All assertions passed"
}
included: /opt/k8s/git/kubeadm-ha/roles/prepare/base/tasks/common.yml for 192.168.85.131

TASK [prepare/base : 统一时区为 Asia/Shanghai] **************************************
ok: [192.168.85.131]

TASK [prepare/base : 禁用系统 swap] ************************************************
changed: [192.168.85.131]

TASK [prepare/base : 删除 fstab swap 相关配置] ***************************************
changed: [192.168.85.131]

TASK [prepare/base : 加载内核模块] ***************************************************
ok: [192.168.85.131] => (item=sunrpc)
changed: [192.168.85.131] => (item=ip_vs)
changed: [192.168.85.131] => (item=ip_vs_rr)
changed: [192.168.85.131] => (item=ip_vs_sh)
changed: [192.168.85.131] => (item=ip_vs_wrr)
changed: [192.168.85.131] => (item=br_netfilter)

TASK [prepare/base : 加载nf_conntrack for kernel < 4.19] *************************
ok: [192.168.85.131]

TASK [prepare/base : 设置 systemd-modules-load 配置] *******************************
changed: [192.168.85.131]

TASK [prepare/base : 启动/重启 systemd-modules-load] *******************************
changed: [192.168.85.131]

TASK [prepare/base : 设置系统参数] ***************************************************
changed: [192.168.85.131]

TASK [prepare/base : 生效系统参数] ***************************************************
changed: [192.168.85.131]

TASK [prepare/base : 优化 nfs clinet 配置] *****************************************
changed: [192.168.85.131]

TASK [prepare/base : 生效 nfs clinet 配置] *****************************************
changed: [192.168.85.131]

TASK [prepare/base : 添加集群节点 hostname 信息到 hosts 文件中] ****************************
ok: [192.168.85.131]

TASK [prepare/base : 确认 hosts 文件中 localhost ipv4 配置正确] *************************
changed: [192.168.85.131]

TASK [prepare/base : 确认 hosts 文件中 localhost ipv6 配置正确] *************************
changed: [192.168.85.131]

TASK [prepare/base : 创建 systemd 配置目录] ******************************************
changed: [192.168.85.131]

TASK [prepare/base : 设置系统 ulimits] *********************************************
changed: [192.168.85.131]
included: /opt/k8s/git/kubeadm-ha/roles/prepare/base/tasks/centos.yml for 192.168.85.131

TASK [prepare/base : 判断 firewalld 是否安装] ****************************************
changed: [192.168.85.131]

TASK [prepare/base : 禁用防火墙] ****************************************************
changed: [192.168.85.131]

TASK [prepare/base : 设置 yum obsoletes 值为 0] ************************************
changed: [192.168.85.131]

TASK [prepare/base : 添加 epel 仓库] ***********************************************
changed: [192.168.85.131]

TASK [prepare/base : 刷新 yum 缓存] ************************************************
 [WARNING]: Consider using the yum module rather than running 'yum'.  If you
need to use command because yum is insufficient you can add 'warn: false' to
this command task or set 'command_warnings=False' in ansible.cfg to get rid of
this message.

fatal: [192.168.85.131]: FAILED! => {"changed": true, "cmd": "yum clean all && yum makecache fast", "delta": "0:00:00.697239", "end": "2020-11-23 17:29:17.150879", "msg": "non-zero return code", "rc": 2, "start": "2020-11-23 17:29:16.453640", "stderr": "usage: yum makecache [-c [config file]] [-q] [-v] [--version]\n                     [--installroot [path]] [--nodocs] [--noplugins]\n                     [--enableplugin [plugin]] [--disableplugin [plugin]]\n                     [--releasever RELEASEVER] [--setopt SETOPTS]\n                     [--skip-broken] [-h] [--allowerasing] [-b | --nobest]\n                     [-C] [-R [minutes]] [-d [debug level]] [--debugsolver]\n                     [--showduplicates] [-e ERRORLEVEL] [--obsoletes]\n                     [--rpmverbosity [debug level name]] [-y] [--assumeno]\n                     [--enablerepo [repo]] [--disablerepo [repo] | --repo\n                     [repo]] [--enable | --disable] [-x [package]]\n                     [--disableexcludes [repo]] [--repofrompath [repo,path]]\n                     [--noautoremove] [--nogpgcheck] [--color COLOR]\n                     [--refresh] [-4] [-6] [--destdir DESTDIR]\n                     [--downloadonly] [--comment COMMENT] [--bugfix]\n                     [--enhancement] [--newpackage] [--security]\n                     [--advisory ADVISORY] [--bz BUGZILLA] [--cve CVES]\n                     [--sec-severity {Critical,Important,Moderate,Low}]\n                     [--forcearch ARCH] [--timer]\nyum makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer')", "stderr_lines": ["usage: yum makecache [-c [config file]] [-q] [-v] [--version]", "                     [--installroot [path]] [--nodocs] [--noplugins]", "                     [--enableplugin [plugin]] [--disableplugin [plugin]]", "                     [--releasever RELEASEVER] [--setopt SETOPTS]", "                     [--skip-broken] [-h] [--allowerasing] [-b | --nobest]", "                     [-C] [-R [minutes]] [-d [debug level]] [--debugsolver]", "                     [--showduplicates] [-e ERRORLEVEL] [--obsoletes]", "                     [--rpmverbosity [debug level name]] [-y] [--assumeno]", "                     [--enablerepo [repo]] [--disablerepo [repo] | --repo", "                     [repo]] [--enable | --disable] [-x [package]]", "                     [--disableexcludes [repo]] [--repofrompath [repo,path]]", "                     [--noautoremove] [--nogpgcheck] [--color COLOR]", "                     [--refresh] [-4] [-6] [--destdir DESTDIR]", "                     [--downloadonly] [--comment COMMENT] [--bugfix]", "                     [--enhancement] [--newpackage] [--security]", "                     [--advisory ADVISORY] [--bz BUGZILLA] [--cve CVES]", "                     [--sec-severity {Critical,Important,Moderate,Low}]", "                     [--forcearch ARCH] [--timer]", "yum makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer')"], "stdout": "39 文件已删除", "stdout_lines": ["39 文件已删除"]}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
192.168.85.131             : ok=47   changed=17   unreachable=0    failed=1    skipped=14   rescued=0    ignored=0   

[root@localhost kubeadm-ha]# kubectl get cs

**Comment by TimeBye** [comment]
你好，暂不支持CentOS8

**Comment by Cutie-Sakura** [comment]
在 centos7 中 安装先是报错，缺拉pip的一个什么包， 安装解决后，现在又报错
TASK [load-balancer : Openresty lb | 拉取相关镜像] ***************************************************************
failed: [192.168.85.134] (item=registry.cn-shanghai.aliyuncs.com/kubeadm-ha/openresty_openresty:1.15.8.3-alpine) => {"ansible_loop_var": "item", "changed": true, "cmd": "docker pull registry.cn-shanghai.aliyuncs.com/kubeadm-ha/openresty_openresty:1.15.8.3-alpine", "delta": "0:00:15.056241", "end": "2020-11-23 15:50:08.310547", "item": "registry.cn-shanghai.aliyuncs.com/kubeadm-ha/openresty_openresty:1.15.8.3-alpine", "msg": "non-zero return code", "rc": 1, "start": "2020-11-23 15:49:53.254306", "stderr": "Error response from daemon: Get https://registry.cn-shanghai.aliyuncs.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", "stderr_lines": ["Error response from daemon: Get https://registry.cn-shanghai.aliyuncs.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"], "stdout": "", "stdout_lines": []}
failed: [192.168.85.134] (item=registry.aliyuncs.com/k8sxio/pause:3.2) => {"ansible_loop_var": "item", "changed": true, "cmd": "docker pull registry.aliyuncs.com/k8sxio/pause:3.2", "delta": "0:00:22.412583", "end": "2020-11-23 15:50:30.836641", "item": "registry.aliyuncs.com/k8sxio/pause:3.2", "msg": "non-zero return code", "rc": 1, "start": "2020-11-23 15:50:08.424058", "stderr": "Error response from daemon: Get https://registry.aliyuncs.com/v2/k8sxio/pause/manifests/3.2: dial tcp 120.55.105.209:443: connect: connection refused", "stderr_lines": ["Error response from daemon: Get https://registry.aliyuncs.com/v2/k8sxio/pause/manifests/3.2: dial tcp 120.55.105.209:443: connect: connection refused"], "stdout": "", "stdout_lines": []}
是什么原因啊
[root@localhost kubeadm-ha]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[root@localhost kubeadm-ha]# cat /proc/version
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020
[root@localhost kubeadm-ha]#

**Comment by TimeBye** [comment]
`dial tcp 120.55.105.209:443: connect: connection refused`   请排查节点连接阿里云的镜像库网络是否正常

**Comment by TimeBye** [comment]
你好，项目master分支已支持CentOS8进行集群安装；安装前建议替换CentOS8默认yum源为阿里云镜像源，以避免网络问题

替换方式可参考：https://developer.aliyun.com/mirror/centos

**Comment by TimeBye** [comment]
当前kube-proxy并不支持 nftables 后端，故CentOS8组件的集群仅做试验使用，请勿用于生产环境。
https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#%E7%A1%AE%E4%BF%9D-iptables-%E5%B7%A5%E5%85%B7%E4%B8%8D%E4%BD%BF%E7%94%A8-nftables-%E5%90%8E%E7%AB%AF
