### ISSUE TITLE
containerd 支持

### ISSUE THREAD

**Issue by carllhw** [TimeBye/kubeadm-ha#29]
[Don't Panic: Kubernetes and Docker](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/)

**Comment by TimeBye** [comment]
你好，develop 分支已做 containerd 支持，欢迎测试体验

https://github.com/TimeBye/kubeadm-ha/tree/develop

**Comment by carllhw** [comment]
会支持docker -> containerd的操作吗

**Comment by TimeBye** [comment]
可以支持，应该没太大问题。但由于crictl不支持镜像导入导出，故离线环境使用containerd作为容器运行时需自行搭建镜像仓库并推送相关镜像后才能使用本项目。

**Comment by carllhw** [comment]
> 可以支持，应该没太大问题。但由于crictl不支持镜像导入导出，故离线环境使用containerd作为容器运行时需自行搭建镜像仓库并推送相关镜像后才能使用本项目。

crt image import

可以用这个

**Comment by TimeBye** [comment]
谢谢提示   已测试成功

**Comment by TimeBye** [comment]
功能已实现，欢迎使用

https://github.com/TimeBye/kubeadm-ha/blob/master/docs/09-Docker%E5%88%87%E6%8D%A2%E4%B8%BAcontainerd.md
