### ISSUE TITLE
在虚拟机部署单机版k8s环境时报了一些错误，请问是否正常

### ISSUE THREAD

**Issue by AIBUSHISHOU** [TimeBye/kubeadm-ha#3]
虚拟机环境：2核 4G内存(自动部署脚本好像检测的就是这个)
报错如下：
TASK [plugins/ingress-controller : 轮询等待 nginx-ingress-controller 运行] ***********
fatal: [192.168.68.130]: FAILED! => {"attempts": 12, "changed": true, "cmd": "kubectl get pod --all-namespaces -o wide | grep 'nginx-ingress' | awk '{print $4}'", "delta": "0:00:00.089931", "end": "2019-06-26 20:41:20.396806", "rc": 0, "start": "2019-06-26 20:41:20.306875", "stderr": "", "stderr_lines": [], "stdout": "ContainerCreating", "stdout_lines": ["ContainerCreating"]}
...ignoring

TASK [plugins/metrics-server : 轮询等待 metrics-server 运行] *************************
fatal: [192.168.68.130]: FAILED! => {"attempts": 12, "changed": true, "cmd": "kubectl get pod --all-namespaces -o wide | grep 'metrics-server' | awk '{print $4}'", "delta": "0:00:00.081390", "end": "2019-06-26 20:42:24.123638", "rc": 0, "start": "2019-06-26 20:42:24.042248", "stderr": "", "stderr_lines": [], "stdout": "ContainerCreating", "stdout_lines": ["ContainerCreating"]}
...ignoring

TASK [plugins/kubernetes-dashboard : 轮询等待 kubernetes-dashboard 运行] *************
fatal: [192.168.68.130]: FAILED! => {"attempts": 12, "changed": true, "cmd": "kubectl get pod --all-namespaces -o wide | grep 'kubernetes-dashboard' | awk '{print $4}'", "delta": "0:00:00.060985", "end": "2019-06-26 20:43:27.131886", "rc": 0, "start": "2019-06-26 20:43:27.070901", "stderr": "", "stderr_lines": [], "stdout": "ContainerCreating", "stdout_lines": ["ContainerCreating"]}
...ignoring

**Comment by TimeBye** [comment]
这是由于拉取镜像过慢导致的，不用管`ignoring`掉的错误哈，k8s会自动慢慢拉取相应的镜像

**Comment by AIBUSHISHOU** [comment]
> 这是由于拉取镜像过慢导致的，不用管`ignoring`掉的错误哈，k8s会自动慢慢拉取相应的镜像

好的，谢谢！顺便问两个问题：
1. 拉取镜像过慢的话，是因为网速的原因还是镜像资源的原因？
2. 我看网上说，搭建k8s集群的话，内存最基本是2GB，这里的4GB的检测设置是在哪个文件中写的？
还请您解答下。

**Comment by TimeBye** [comment]
你好：
1. 我脚本里面的镜像都是通过 [azk8s.cn](http://mirror.azure.cn/) 进行加速代理的，拉取镜像过慢的话，在国内就只有网速问题了。  
2.节点物理资源是有相关校验的，详见[这里]( https://github.com/TimeBye/kubeadm-ha/blob/master/roles/prepare/base/tasks/verify_node.yml)

**Comment by AIBUSHISHOU** [comment]
> 你好：
> 
> 1. 我脚本里面的镜像都是通过 [azk8s.cn](http://mirror.azure.cn/) 进行加速代理的，拉取镜像过慢的话，在国内就只有网速问题了。
> 
> 2.节点物理资源是有相关校验的，详见[这里](https://github.com/TimeBye/kubeadm-ha/blob/master/roles/prepare/base/tasks/verify_node.yml)

非常感谢！我会持续关注和使用您提供的脚本的。

**Comment by TimeBye** [comment]
谢谢支持，多多交流
