### ISSUE TITLE
k8s1.20安装nfs问题

### ISSUE THREAD

**Issue by it00021hot** [TimeBye/kubeadm-ha#32]
安装nfs无法创建pv，报错信息如下：  Warning  FailedMount  2m14s                kubelet            Unable to attach or mount volumes: unmounted volumes=[nfs-client-root], unattached volumes=[nfs-client-provisioner-sa-token-9frf5 nfs-client-root]: timed out waiting for the condition

**Comment by TimeBye** [comment]
请手动尝试是否可以在节点上直接mount nfs

**Comment by it00021hot** [comment]
更换镜像后解决了，谢谢！
