### ISSUE TITLE
离线包，链接页面找了半天也没看到有下载链接

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#33]
如题，帮忙看下

**Comment by TimeBye** [comment]
![image](https://user-images.githubusercontent.com/22651579/105132347-beec3200-5b25-11eb-91c1-c700c008ef43.png)
![image](https://user-images.githubusercontent.com/22651579/105132380-cdd2e480-5b25-11eb-8348-a5618219a1b0.png)

**Comment by li-sen** [comment]
![Uploading image.png…]()

**Comment by li-sen** [comment]
链接都是打不开的~

**Comment by li-sen** [comment]
![Uploading image.png…]()

**Comment by li-sen** [comment]
![Uploading image.png…]()

**Comment by li-sen** [comment]
这链接下倒是能下 就是速度有点慢，建议找个阿里云oss 放下

**Comment by TimeBye** [comment]
嗯   后面会对这一块进行优化  谢谢反馈

**Comment by li-sen** [comment]
之前老版本的包还有吗？比如1.15.x

**Comment by TimeBye** [comment]
没有的   从1.20开始  才使用github actions进行离线包构建，若你需要老版本可以clone本项目回退代码至1.15版本的kubernetes自行进行离线包构建

**Comment by li-sen** [comment]
了解了，我等会试这跑下~

**Comment by li-sen** [comment]
现在arm环境也多了，建议离线包也支持下~

**Comment by TimeBye** [comment]
后面会慢慢的进行支持的，敬请期待

**Comment by li-sen** [comment]
1.16+ 是可以开启 api兼容参数的吧？ 我们很多资源对象都是 extensions/v1beta1  xxxx 的

**Comment by TimeBye** [comment]
从 1.16 开始 是直接移除了，建议尽快进行更新


https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by li-sen** [comment]
api 可以加参数开启的，不知道1.20是不是直接删了~

**Comment by TimeBye** [comment]
可以尝试打开这里的注释，将参数添加在这里

https://github.com/TimeBye/kubeadm-ha/blob/956203ec316dea4af790fffadd462d8ab09c3851/example/variables.yaml#L311

**Comment by li-sen** [comment]
1.20 --runtime-config=api/all=true  就行了吧

**Comment by li-sen** [comment]
离线包用 docker runtime 也支持的吧

**Comment by TimeBye** [comment]
> 离线包用 docker runtime 也支持的吧

支持的

**Comment by TimeBye** [comment]
> 1.20 --runtime-config=api/all=true 就行了吧

按文档设置吧   这一块我们没有这个需求，没有配置过

**Comment by li-sen** [comment]
```bash
; 私有云：
;    VIP 负载模式：
;       也就是负载均衡器 + keepalived 模式，比如常用的 haproxy + keepalived。
;       本脚本中负载均衡器有 nginx、openresty、haproxy、envoy 可供选择，设置 lb_mode 即可进行任意切换。
;       设置 lb_kube_apiserver_ip 即表示启用 keepalived，请先与服务器提供部门协商保留一个IP作为 lb_kube_apiserver_ip，
;       一般 lb 节点组中有两个节点就够了，lb节点组中第一个节点为 keepalived 的 master 节点，剩下的都为 backed 节点。
;
;    节点本地负载模式：
;       只启动负载均衡器，不启用 keepalived（即不设置 lb_kube_apiserver_ip），
;       此时 kubelet 链接 apiserver 地址为 127.0.0.1:lb_kube_apiserver_port。
;       使用此模式时请将 lb 节点组置空。
;
; 公有云：
;    不推荐使用 slb 模式，建议直接使用节点本地负载模式。
;    若使用 slb 模式，请先使用节点本地负载模式进行部署，
;    部署成功后再切换至 slb 模式：
;       将 lb_mode 修改为 slb，将 lb_kube_apiserver_ip 设置为购买到的 slb 内网ip，
;       修改 lb_kube_apiserver_port 为 slb 监听端口。
;    再次运行初始化集群脚本即可切换至 slb 模式。
[lb]

```
你这lb 是 啥意思， 比如我有两个节点 想装 nginx+keepalive 这里该怎么填， 比如 172.19.70.38   172.19.70.39

**Comment by TimeBye** [comment]
离线部署不支持nginx+keepalive，因为没有离线keepalive的镜像，若再加上这些可选包那么离线文件将会更大。离线时负载模式、网络插件、ingress-controller都不可更换，请使用默认值。

lb组就是安装负载均衡器和keepalive的组，在线安装时想装 nginx+keepalive，使用172.19.70.38 172.19.70.39两个节点，则 lb 中填写这两个节点即可。

**Comment by li-sen** [comment]
了解了

**Comment by li-sen** [comment]
```bash
  ![](https://i.loli.net/2020/12/22/fcQeuvXxjqk6o1a.png)
``` 
离线安装文档这里空了你自己补全下~

**Comment by TimeBye** [comment]
文档已更新

https://github.com/TimeBye/kubeadm-ha/blob/master/docs/08-%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85.md
