### ISSUE TITLE
离线部署完成  kubectl get cs 异常

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#36]
[root@jy-master01 ~]# kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused
etcd-2               Healthy     {"health":"true"}
etcd-0               Healthy     {"health":"true"}
etcd-1               Healthy     {"health":"true"}

**Comment by li-sen** [comment]
解决方法：修改master节点配置文件
vim /etc/kubernetes/manifests/kube-controller-manager.yaml
vim /etc/kubernetes/manifests/kube-scheduler.yaml
# 注释掉port=0这一行

**Comment by TimeBye** [comment]
`kubectl get cs` 已弃用，增加`port=0`是为了符合 CIS kubernetes 安全白皮书要求而添加。不推荐开启此http端口。

**Comment by li-sen** [comment]
废弃了？ 有替代的 命令？

**Comment by TimeBye** [comment]
直接查看相关组件pod运行状态即可
```
kubectl get po -n kube-system
```

参考：
https://github.com/kubernetes/enhancements/issues/553
https://github.com/kubernetes-sigs/kind/issues/1998
