### ISSUE TITLE
离线部署建议把镜像仓库引进来

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#37]
是不是得先起一个registry，把所有的镜像推上去，在 variables.yaml 定义好仓库地址，所有的镜像都从本地化的registry拉取，
不引进registry的话，导入本地的镜像会被垃圾回收，新加worker也需要一个个去导入镜像太麻烦了，pod切换到新节点没镜像还会起不来

**Comment by TimeBye** [comment]
嗯   这个前期也有考虑到  后面会继续优化

**Comment by TimeBye** [comment]
使用registry托管镜像已支持，欢迎测试及使用

**Comment by li-sen** [comment]
我测试下

**Comment by li-sen** [comment]
测试通过点赞~
