### ISSUE TITLE
镜像同步问题

### ISSUE THREAD

**Issue by it00021hot** [TimeBye/kubeadm-ha#40]
参照您的项目使用的setzero/images-sync:0.3.1镜像同步到harbor私库报错，我这私库是可以公网访问的，请问这个镜像的源码开源的吗，想看看是什么问题

**Comment by TimeBye** [comment]
报的什么错呢？

**Comment by TimeBye** [comment]
我把images-sync的代码整合到了这个库中，可以参考一下这个库

https://github.com/TimeBye/registry-manager

**Comment by it00021hot** [comment]
同步到阿里云是可以的，同步到私库不行，我看看代码试试能不能找到原因

**Comment by TimeBye** [comment]
你的harbor是什么版本？  2.0以下的版本是不行的

**Comment by it00021hot** [comment]
额，我是1.9.3

**Comment by TimeBye** [comment]
2.0以下版本harbor不支持oci，但是我代码里面写死了--all标记同步所有cpu架构镜像。我重新打个可以禁用的版本吧，弄好给你回复。

**Comment by TimeBye** [comment]
将镜像直接替换成  `setzero/images-sync:0.3.2`  即可

**Comment by it00021hot** [comment]
好的，谢谢

**Comment by it00021hot** [comment]
好像还是不行

E0129 09:13:31.684665      33 sync.go:96] 同步镜像出错：time="2021-01-29T09:13:30Z" level=fatal msg="Error writing manifest: Error uploading manifest 0.8.0 to harbor.prod.k8s.lesso.com/kubeadm-ha/pause: received unexpected HTTP status: 500 Internal Server Error"

**Comment by it00021hot** [comment]
直接用skopeo copy到私库提示完成了，但仓库里没有，这harbor版本应该不可以

**Comment by it00021hot** [comment]
skopeo list-tags 可以获取到仓库内的tag列表，docker pull也可以拉，界面就是看不到，神奇了

**Comment by TimeBye** [comment]
是的  会出现这种情况，  2.0以下harbor是根据registry发送的webhook创建的数据库数据（也就是harbor界面上的列表），在推送镜像很频繁的时候可能有网络或者服务无法同时处理那么多请求而导致数据库数据未创建成功所以看不到。
