### ISSUE TITLE
集群初始化失败

### ISSUE THREAD

**Issue by chen5041** [TimeBye/kubeadm-ha#41]
TASK [prepare/base : 清除 yum 缓存] *********************************************************************************************************************************************************************************
task path: /etc/ansible/roles/prepare/base/tasks/centos.yml:28
fatal: [cxs-master01]: FAILED! => {
    "changed": true,
    "cmd": [
        "yum",
        "clean",
        "all"
    ],
    "delta": "0:00:00.388357",
    "end": "2021-02-04 18:31:53.233119",
    "invocation": {
        "module_args": {
            "_raw_params": "yum clean all",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": false
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-02-04 18:31:52.844762",
    "stderr": "There are no enabled repos.\n Run \"yum repolist all\" to see the repos you have.\n To enable Red Hat Subscription Management repositories:\n     subscription-manager repos --enable <repo>\n To enable custom repositories:\n     yum-config-manager --enable <repo>",
    "stderr_lines": [
        "There are no enabled repos.",
        " Run \"yum repolist all\" to see the repos you have.",
        " To enable Red Hat Subscription Management repositories:",
        "     subscription-manager repos --enable <repo>",
        " To enable custom repositories:",
        "     yum-config-manager --enable <repo>"
    ],
    "stdout": "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile",
    "stdout_lines": [
        "Loaded plugins: fastestmirror",
        "Loading mirror speeds from cached hostfile"
    ]
}
Using module file /usr/lib/python3.8/site-packages/ansible/modules/command.py
Pipelining is enabled.

**Comment by TimeBye** [comment]
请提供你所使用的os及版本号

**Comment by chen5041** [comment]
> 请提供你所使用的os及版本号

这个问题已经解决了，我用的是centos7.8， kubernetes1.20.1版本; 这个问题是因为之前有运行过一次，备份了/etc/yum.repos.d/目录，导致我第二次运行找不到这个目录了；所以报错了;
