### ISSUE TITLE
两节点同时是master worker部署失败

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#45]
如题，我只有两台机器，两节点同时是master worker但部署失败
![image](https://user-images.githubusercontent.com/33471335/108811643-948c0980-75e8-11eb-8877-b62de5a4a13e.png)

只写master角色 也不行，
![image](https://user-images.githubusercontent.com/33471335/108811699-abcaf700-75e8-11eb-9eed-21a348603512.png)

**Comment by TimeBye** [comment]
请按issues模板提交问题，谢谢配合

**Comment by li-sen** [comment]
你这模板要填东西太多了，能简单点吗。。。。
