### ISSUE TITLE
chrony 不建议作为默认安装选项

### ISSUE THREAD

**Issue by carllhw** [TimeBye/kubeadm-ha#47]
https://github.com/TimeBye/kubeadm-ha/blob/38be5d5b0d2edee08e2968bc6da9721f9ba096ac/90-init-cluster.yml#L31-L34

因为客户可能已安装了chrony，并有自建的chrony server，建议作为可选项。chrony更建议作为主机安装的方式，容器部署的存在服务器有问题，无法同步时间。

**Comment by TimeBye** [comment]
https://github.com/TimeBye/kubeadm-ha/commit/8ce6b312d0db06826aab3326215a95ee0add3540

已将chrony设置为默认不安装；chrony容器部署还未发现无法同步时间的问题。
