### ISSUE TITLE
coredns无法pull，是不是地址不对了

### ISSUE THREAD

**Issue by linjun0703** [TimeBye/kubeadm-ha#48]
TASK [kube-master : 开始拉取 master 节点相关镜像] *********************************************************************************************************
changed: [192.168.0.11] => (item=registry.aliyuncs.com/kubeadm-ha/kube-apiserver:v1.20.4)
changed: [192.168.0.11] => (item=registry.aliyuncs.com/kubeadm-ha/kube-controller-manager:v1.20.4)
changed: [192.168.0.11] => (item=registry.aliyuncs.com/kubeadm-ha/kube-scheduler:v1.20.4)
changed: [192.168.0.11] => (item=registry.aliyuncs.com/kubeadm-ha/kube-proxy:v1.20.4)
changed: [192.168.0.11] => (item=registry.aliyuncs.com/kubeadm-ha/pause:3.4.1)
failed: [192.168.0.11] (item=registry.aliyuncs.com/kubeadm-ha/coredns/coredns:v1.8.0) => {"ansible_loop_var": "item", "changed": true, "cmd": "docker pull registry.aliyuncs.com/kubeadm-ha/coredns/coredns:v1.8.0", "delta": "0:00:00.476402", "end": "2021-04-11 20:54:51.240249", "item": "registry.aliyuncs.com/kubeadm-ha/coredns/coredns:v1.8.0", "msg": "non-zero return code", "rc": 1, "start": "2021-04-11 20:54:50.763847", "stderr": "Error response from daemon: manifest for registry.aliyuncs.com/kubeadm-ha/coredns/coredns:v1.8.0 not found: manifest unknown: manifest unknown", "stderr_lines": ["Error response from daemon: manifest for registry.aliyuncs.com/kubeadm-ha/coredns/coredns:v1.8.0 not found: manifest unknown: manifest unknown"], "stdout": "", "stdout_lines": []}

**Comment by TimeBye** [comment]
官方还没有推这个镜像，再等等吧，或者先安装低版本的kubernetes

![image](https://user-images.githubusercontent.com/22651579/114305503-e510e500-9b0a-11eb-82e3-13e1a199213c.png)

**Comment by TimeBye** [comment]
额，为什么我这边测试拉取的是1.7.0，你的是v1.8.0   

![image](https://user-images.githubusercontent.com/22651579/114329775-d100ce00-9b72-11eb-9316-33428069095e.png)

**Comment by TimeBye** [comment]
CoreDNS镜像在 1.21.0 版本中更新至 k8s.gcr.io/coredns/coredns ，现已同步镜像，至于你这边为什么1.20.4版本去拉取的coredns/coredns:v1.8.0还请提供更多信息进行分析

https://github.com/kubernetes/kubernetes/pull/96429

**Comment by linjun0703** [comment]
我又拉了一下你这个最新的代码，还是老问题。需要我提供哪些信息呢？

**Comment by TimeBye** [comment]
你好，这个镜像已经有了哦   不应该还有问题呢

![image](https://user-images.githubusercontent.com/22651579/114355352-f1944c80-9ba1-11eb-9667-295b530458b6.png)

**Comment by linjun0703** [comment]
我只改了一个配置文件  hosts.m-master.ip.ini：


; 将所有节点的信息在这里填写
;    第一个字段                  为节点内网IP，部署完成后为 kubernetes 节点 nodeName
;    第二个字段 ansible_port     为节点 sshd 监听端口
;    第三个字段 ansible_user     为节点远程登录用户名
;    第四个字段 ansible_ssh_pass 为节点远程登录用户密码
[all]
192.168.0.11 ansible_port=22 ansible_user="root" ansible_ssh_pass="linux"
192.168.0.12 ansible_port=22 ansible_user="root" ansible_ssh_pass="linux"
192.168.0.13 ansible_port=22 ansible_user="root" ansible_ssh_pass="linux"
192.168.0.14 ansible_port=22 ansible_user="root" ansible_ssh_pass="linux"

; 私有云：
;    VIP 负载模式：
;       也就是负载均衡器 + keepalived 模式，比如常用的 haproxy + keepalived。
;       本脚本中负载均衡器有 nginx、openresty、haproxy、envoy 可供选择，设置 lb_mode 即可进行任意切换。
;       设置 lb_kube_apiserver_ip 即表示启用 keepalived，请先与服务器提供部门协商保留一个IP作为 lb_kube_apiserver_ip，
;       一般 lb 节点组中有两个节点就够了，lb节点组中第一个节点为 keepalived 的 master 节点，剩下的都为 backed 节点。
;
;    节点本地负载模式：
;       只启动负载均衡器，不启用 keepalived（即不设置 lb_kube_apiserver_ip），
;       此时 kubelet 链接 apiserver 地址为 127.0.0.1:lb_kube_apiserver_port。
;       使用此模式时请将 lb 节点组置空。
;
; 公有云：
;    不推荐使用 slb 模式，建议直接使用节点本地负载模式。
;    若使用 slb 模式，请先使用节点本地负载模式进行部署，
;    部署成功后再切换至 slb 模式：
;       将 lb_mode 修改为 slb，将 lb_kube_apiserver_ip 设置为购买到的 slb 内网ip，
;       修改 lb_kube_apiserver_port 为 slb 监听端口。
;    再次运行初始化集群脚本即可切换至 slb 模式。
[lb]

; 注意etcd集群必须是1,3,5,7...奇数个节点
[etcd]
192.168.0.11
192.168.0.12
192.168.0.13

[kube-master]
192.168.0.11
192.168.0.12
192.168.0.13

[kube-worker]
192.168.0.11
192.168.0.12
192.168.0.13
192.168.0.14

; 预留组，后续添加master节点使用
[new-master]

; 预留组，后续添加worker节点使用
[new-worker]

; 预留组，后续添加etcd节点使用
[new-etcd]

; 预留组，后续删除worker角色使用
[del-worker]

; 预留组，后续删除master角色使用
[del-master]

; 预留组，后续删除etcd角色使用
[del-etcd]

; 预留组，后续删除节点使用
[del-node]

;-------------------------------------- 以下为基础信息配置 ------------------------------------;
[all:vars]
; 是否跳过节点物理资源校验，Master节点要求2c2g以上，Worker节点要求2c4g以上
skip_verify_node=false
; kubernetes版本
kube_version="1.20.4"

; 容器运行时类型，可选项：containerd，docker；默认 containerd
container_manager="containerd"

; 负载均衡器
;   有 nginx、openresty、haproxy、envoy  和 slb 可选，默认使用 nginx
lb_mode="nginx"
; 使用负载均衡后集群 apiserver ip，设置 lb_kube_apiserver_ip 变量，则启用负载均衡器 + keepalived
; lb_kube_apiserver_ip="192.168.0.15"
; 使用负载均衡后集群 apiserver port
lb_kube_apiserver_port="8443"

; 网段选择：pod 和 service 的网段不能与服务器网段重叠，
; 若有重叠请配置 `kube_pod_subnet` 和 `kube_service_subnet` 变量设置 pod 和 service 的网段，示例参考：
;    如果服务器网段为：10.0.0.1/8
;       pod 网段可设置为：192.168.0.0/18
;       service 网段可设置为 192.168.64.0/18
;    如果服务器网段为：172.16.0.1/12
;       pod 网段可设置为：10.244.0.0/18
;       service 网段可设置为 10.244.64.0/18
;    如果服务器网段为：192.168.0.1/16
;       pod 网段可设置为：10.244.0.0/18
;       service 网段可设置为 10.244.64.0/18
; 集群pod ip段，默认掩码位 18 即 16384 个ip
kube_pod_subnet="10.244.0.0/18"
; 集群service ip段
kube_service_subnet="10.244.64.0/18"
; 分配给节点的 pod 子网掩码位，默认为 24 即 256 个ip，故使用这些默认值可以纳管 16384/256=64 个节点。
kube_network_node_prefix="24"

; node节点最大 pod 数。数量与分配给节点的 pod 子网有关，ip 数应大于 pod 数。
; https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr
kube_max_pods="110"

; 集群网络插件，目前支持flannel,calico
network_plugin="calico"

; 若服务器磁盘分为系统盘与数据盘，请修改以下路径至数据盘自定义的目录。
; Kubelet 根目录
kubelet_root_dir="/var/lib/kubelet"
; docker容器存储目录
docker_storage_dir="/var/lib/docker"
; containerd容器存储目录
containerd_storage_dir="/var/lib/containerd"
; Etcd 数据根目录
etcd_data_dir="/var/lib/etcd"

**Comment by TimeBye** [comment]
你现在执行的报错截图发一个呢

**Comment by linjun0703** [comment]
额，拉镜像的问题解决了，现在应该是版本不匹配了：
![image](https://user-images.githubusercontent.com/3870466/114355698-5e0f4b80-9ba2-11eb-8ee7-d1c165637a7d.png)

**Comment by TimeBye** [comment]
在执行本项目前  服务器上已经安装docker了吗？是的话 请卸载每个服务器上的docker后重试

**Comment by linjun0703** [comment]
对，已经安装了docker，我重新卸载试试看。待会再来

**Comment by linjun0703** [comment]
已经卸载了，还是不行


![image](https://user-images.githubusercontent.com/3870466/114380995-3c6f8d80-9bbd-11eb-9583-4dc05f86ff69.png)

**Comment by linjun0703** [comment]
the kubelet version is higher than the control plane version  ？是脚本里面kubelet的版本问题？

**Comment by TimeBye** [comment]
你自己在 192.168.0.11 上安装过 kubelet、kubeadm 过吗？请先卸载后重试

**Comment by linjun0703** [comment]
卸载以后已经安装成功，谢谢
