### ISSUE TITLE
加节点

### ISSUE THREAD

**Issue by sky-daiji** [TimeBye/kubeadm-ha#5]
@TimeBye   建议补全增加 节点的文档吧，不知道咋操作

**Comment by TimeBye** [comment]
骚年，加节点仅需三步：
1. 修改主机清单文件`example/hosts.m-master.ip.ini`，在`[all]`分区加上新节点的信息。
2. 修改主机清单文件`example/hosts.m-master.ip.ini`，在`[new-worker]`分区加上新节点的信息。
3. 执行`ansible-playbook -i example/hosts.m-master.ip.ini 92-add-worker.yml`即可
