### ISSUE TITLE
怎么更改离线包里的镜像

### ISSUE THREAD

**Issue by WinterZhou** [TimeBye/kubeadm-ha#50]
想要更改离线包里面的镜像，支持自定义构建离线包吗？

**Comment by TimeBye** [comment]
https://github.com/TimeBye/kubeadm-ha/tree/master/offline

制作离线包的相关文件在这里，参考修改即可

**Comment by WinterZhou** [comment]
> https://github.com/TimeBye/kubeadm-ha/tree/master/offline
> 
> 制作离线包的相关文件在这里，参考修改即可

这个镜像，setzero/kubeadm-ha:1.20.4-base，是根据Dockerfile.base构建出来的吗？

**Comment by TimeBye** [comment]
是的

**Comment by WinterZhou** [comment]
> 是的

感谢！还有一个疑问，/var/lib/registry这个registry是镜像文件吧？是通过手动push到registry容器里面，然后copy出这个资料包吗？

**Comment by TimeBye** [comment]
可查看github action

https://github.com/TimeBye/kubeadm-ha/blob/master/.github/workflows/build-base.yml

**Comment by WinterZhou** [comment]
> 可查看github action
> 
> https://github.com/TimeBye/kubeadm-ha/blob/master/.github/workflows/build-base.yml

感谢！另外想问一句，这部分仓库有考虑用nexus实现吗？自带dashboard可以管理镜像。
