### ISSUE TITLE
CentOS Linux release 8.3.2011，linux内核为4.18.0-240.el8.x86_64

### ISSUE THREAD

**Issue by carllhw** [TimeBye/kubeadm-ha#51]
其中内核模块包含的是nf_conntrack，没有nf_conntrack_ipv4，执行报错。

**Comment by TimeBye** [comment]
已修改逻辑为先加载  nf_conntrack_ipv4 ,若报错则加载 nf_conntrack

https://github.com/TimeBye/kubeadm-ha/blob/master/roles/prepare/base/tasks/common.yml#L29-L41
