### ISSUE TITLE
Audit policy metadata-only rule should include `serviceaccounts/token` resource

### ISSUE THREAD

**Issue by liggitt** [TimeBye/kubeadm-ha#57]
The following files reference a metadata-only audit policy in order to prevent logging request/response contents for sensitive resources:

* https://github.com/TimeBye/kubeadm-ha/blob/master/roles/kube-master/templates/apiserver-audit-policy.yaml.j2

A recent Kubernetes [bugfix](https://github.com/kubernetes/kubernetes/pull/102040) means that audit-logging of subresource requests which previously failed will now log successfully. The `serviceaccounts/token` subresource responds to `TokenRequest` API calls with a newly minted service account token.

The `serviceaccounts/token` resource should also be included in the metadata-only audit policy if credentials are not intended to appear in the audit log:

```yaml
- group: "" # core
  resources: ["secrets", "configmaps", "serviceaccounts/token"]
```

**Comment by TimeBye** [comment]
Thank you for your reminder, this problem is now resolved.

https://github.com/TimeBye/kubeadm-ha/commit/63726b817cbe6d87e7df142c0ba8d755f5a856cf
