### ISSUE TITLE
请问使用本地负载时，master节点为什么还要部署负载均衡

### ISSUE THREAD

**Issue by jinnzy** [TimeBye/kubeadm-ha#59]
**简要描述您所需的功能，功能与什么问题有关**

负载均衡

**描述您想要的解决方案**

master节点不部署负载均衡，只有worker节点部署负载均衡，端口可以统一使用6443，ip使用127.0.0.1或者本地解析域名？

**描述您考虑过的替代方案**

**其他事项**

在此处添加有关该功能的任何其他事项。

**Comment by TimeBye** [comment]
你好，可查阅这里说明文档

https://github.com/TimeBye/kubeadm-ha/blob/master/docs/00-%E5%AE%89%E8%A3%85%E9%A1%BB%E7%9F%A5.md#%E6%9C%AC%E5%9C%B0%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1
