### ISSUE TITLE
高并发环境下内核调整问题

### ISSUE THREAD

**Issue by icezhang88** [TimeBye/kubeadm-ha#66]
集群部署完成后，开启10K多线程测试后台，压测错误率非常高。查看了脚本修改的内核参数，配置的较低，是否要提升下内核的高并发情况的参数

**Comment by TimeBye** [comment]
你好，请问压测是指的压测 kube-apiserver 吗？

**Comment by icezhang88** [comment]
对部署的服务及api-server都做压测，现在是3台阿里云  4核8G  通用性服务器测试  搭建的K8s ,采用仓库的hosts.m-master.ip配置，并且在压测的过程中，max_wait的数据回收速度慢

**Comment by TimeBye** [comment]
脚本中使用的内核参数值为各云厂商推荐的默认值的总结，这一块我也不是很熟息，望大佬能一起进行这一块的调校，共同完善这个脚本

https://github.com/TimeBye/kubeadm-ha/blob/master/roles/prepare/base/templates/95-k8s-sysctl.conf.j2
