### ISSUE TITLE
Restore previous backups

### ISSUE THREAD

**Issue by carllhw** [TimeBye/kubeadm-ha#7]
Restore previous backups from `94-backup-cluster.yml`

**Comment by TimeBye** [comment]
Hello, relevant docs and playbook are in preparation.

**Comment by TimeBye** [comment]
Hi, @carllhw restoring the previous backup function has been completed, welcome to trial.

- Backup Cluster
   ```
   ansible-playbook -i example/hosts.m-master.ip.ini 96-backup-cluster.yml
   ```

- Restore previous backups
   ```
   ansible-playbook -i example/hosts.m-master.ip.ini 97-restore-cluster.yml
   ```
