### ISSUE TITLE
新增worker节点，我看了下执行步骤所有节点上的证书都要重新生成？

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#70]
**缺陷描述**
个人觉得加一个节点，为什么所有节点的证书都要重新生成？？还是我执行的时候需要加--limit 参数？
```bash
ansible-playbook -i my-cluster/inventory.ini -e my-cluster/variables.yaml 81-add-worker.yml --limit jy-worker06
```

离线部署 新增worker 有以下问题：
1. hosts文件没加  172.19.70.36 yum.custom.local registry.custom.local 

2. docker 配置文件   "insecure-registries": ["registry.custom.local:5000"],  也没加

 第三步：执行部署命令，命令如下
    ```yaml
ansible-playbook -i my-cluster/inventory.ini -e my-cluster/variables.yaml 81-add-worker.yml
    ```

**Comment by TimeBye** [comment]
- 为什么所有节点的证书都要重新生成？
   -  因为需要生成新加节点证书直接使用了批量生成证书脚本，所有节点的证书都重新生成并不会产生什么影响。
- 执行的时候需要加--limit 参数吗？
   - 不需要
- 新增worker没有添加hosts、docker 配置文件配置
   - 请排查`my-cluster/variables.yaml`中是否有配置，或者执行时命令中是否指定了该文件

**Comment by TimeBye** [comment]
正确命令为：
```
ansible-playbook -i my-cluster/inventory.ini -e @my-cluster/variables.yaml 81-add-worker.yml
```

**Comment by li-sen** [comment]
我核实下~
