### ISSUE TITLE
nf_conntrack_ipv4 not found

### ISSUE THREAD

**Issue by chinaboy007** [TimeBye/kubeadm-ha#71]
centos 7.5
内核 5.4.92-1.el7.elrepo.x86_64
安装提示nf_conntrack_ipv4 not found ，查了说是最新内核已经将nf_conntrack_ipv4 改名为nf_conntrack了。看看这个问题是否可以修复

**Comment by TimeBye** [comment]
你好，这里并没有问题哈，脚本日志已输出 ignore

**Comment by chinaboy007** [comment]
> 你好，这里并没有问题哈，脚本日志已输出 ignore

https://github.com/kubernetes/kubernetes/issues/70304  4.19以上的内核已经没有 nf_conntrack_ipv4了

**Comment by TimeBye** [comment]
嗯  是的  没有了哈，所以脚本里面ignore了这里

**Comment by chinaboy007** [comment]
> 嗯 是的 没有了哈，所以脚本里面ignore了这里

忽略了，是否会影响开启ipvs？ 

后面vip 起不来。日志如下：
TASK [load-balancer : Nginx lb | 生成 nginx lb 配置文件] *****************************
ok: [192.168.40.202]
ok: [192.168.40.203]

TASK [load-balancer : Nginx lb | 拉取相关镜像] ***************************************
changed: [192.168.40.202] => (item=registry.aliyuncs.com/kubeadm-ha/nginx:1.19-alpine)
changed: [192.168.40.203] => (item=registry.aliyuncs.com/kubeadm-ha/nginx:1.19-alpine)
changed: [192.168.40.203] => (item=registry.aliyuncs.com/kubeadm-ha/pause:3.4.1)
changed: [192.168.40.202] => (item=registry.aliyuncs.com/kubeadm-ha/pause:3.4.1)

TASK [load-balancer : Nginx lb | 生成 nginx lb static pod 文件] ********************
ok: [192.168.40.202]
ok: [192.168.40.203]

TASK [load-balancer : keepalived | 获取网卡名称] *************************************
changed: [192.168.40.202]
changed: [192.168.40.203]

TASK [load-balancer : keepalived | 拉取相关镜像] *************************************
changed: [192.168.40.202] => (item=registry.aliyuncs.com/kubeadm-ha/osixia_keepalived:2.0.20)
changed: [192.168.40.203] => (item=registry.aliyuncs.com/kubeadm-ha/osixia_keepalived:2.0.20)

TASK [load-balancer : keepalived | 生成 static pod 文件] ***************************
changed: [192.168.40.202]
changed: [192.168.40.203]

TASK [load-balancer : 读取 kubelet.conf 文件 stat 信息] ******************************
ok: [192.168.40.202]
ok: [192.168.40.203]
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (12 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (12 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (11 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (11 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (10 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (10 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (9 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (9 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (8 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (8 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (7 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (7 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (6 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (6 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (5 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (5 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (4 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (4 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (3 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (3 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (2 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (2 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (1 retries left).
FAILED - RETRYING: 以轮询的方式等待 nginx 运行完成 (1 retries left).

TASK [load-balancer : 以轮询的方式等待 nginx 运行完成] *************************************
fatal: [192.168.40.203]: FAILED! => {"attempts": 12, "changed": true, "cmd": "nc -z -w 3 127.0.0.1 8443", "delta": "0:00:00.075862", "end": "2021-08-18 17:53:53.604710", "msg": "non-zero return code", "rc": 1, "start": "2021-08-18 17:53:53.528848", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
fatal: [192.168.40.202]: FAILED! => {"attempts": 12, "changed": true, "cmd": "nc -z -w 3 127.0.0.1 8443", "delta": "0:00:00.073057", "end": "2021-08-18 17:53:53.609467", "msg": "non-zero return code", "rc": 1, "start": "2021-08-18 17:53:53.536410", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
192.168.40.201             : ok=52   changed=12   unreachable=0    failed=0    skipped=13   rescued=0    ignored=1   
192.168.40.202             : ok=55   changed=17   unreachable=0    failed=1    skipped=19   rescued=0    ignored=1   
192.168.40.203             : ok=55   changed=17   unreachable=0    failed=1    skipped=19   rescued=0    ignored=1

**Comment by TimeBye** [comment]
你好，不会有什么影响，你这个报错请查看一下nginx容器的日志和runtime的日志

**Comment by chinaboy007** [comment]
> 你好，不会有什么影响，你这个报错请查看一下nginx容器的日志和runtime的日志

我也想查，但没有启动nginx,看不到日志

[root@k8s-m1 ~]# crictl ps
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
[root@k8s-m1 ~]# crictl images
IMAGE                                                TAG                 IMAGE ID            SIZE
registry.aliyuncs.com/kubeadm-ha/nginx               1.19-alpine         a64a6e03b0551       9.83MB
registry.aliyuncs.com/kubeadm-ha/osixia_keepalived   2.0.20              593459a9e605a       25.2MB
registry.aliyuncs.com/kubeadm-ha/pause               3.4.1               0f8457a4c2eca       301kB

**Comment by TimeBye** [comment]
crictl ps -a

crictl logs xxxxx
