### ISSUE TITLE
怎么删除docker的镜像    docker命令不能用 

### ISSUE THREAD

**Issue by icezhang88** [TimeBye/kubeadm-ha#73]
怎么删除docker的镜像    docker命令不能用

**Comment by TimeBye** [comment]
kubelet会自动进行gc，不需要手动去删除镜像

**Comment by TimeBye** [comment]
https://github.com/TimeBye/kubeadm-ha/blob/master/docs/09/%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E8%BF%90%E8%A1%8C%E6%97%B6%E7%BB%84%E4%BB%B6.md


你也可以参考这里进行手动删除镜像
