### ISSUE TITLE
容器可以换成docker 吗  公司之前的架构都是用docker  不用containered  ，这个可以更换吗

### ISSUE THREAD

**Issue by icezhang88** [TimeBye/kubeadm-ha#74]
容器可以换成docker 吗  公司之前的架构都是用docker  不用containered  ，这个可以更换吗

**Comment by TimeBye** [comment]
建议重装系统后重新安装集群

**Comment by icezhang88** [comment]
更改哪个参数可以使用docker呢

**Comment by icezhang88** [comment]
没有在文档里看到呢

**Comment by TimeBye** [comment]
所有的主机清单文件中都有提及，例如

https://github.com/TimeBye/kubeadm-ha/blob/master/example/hosts.m-master.hostname.ini#L79-L80

**Comment by icezhang88** [comment]
好的 非常感谢
