### ISSUE TITLE
求解，有关kubeadmConfig中certSANs的问题

### ISSUE THREAD

**Issue by libincla** [TimeBye/kubeadm-ha#76]
请问一下，在执行`init`初始化之前，先执行证书的生成，我看在`kube-cerificate`的`role`中，有一个`kube-openssl.cnf`的配置文件，文件中已经指定了`IP.1, IP.2, ...IP.N`，为何还要在生成`kubeadm`初始化配置文件的时候，要指定`certSANS`呢？

**Comment by TimeBye** [comment]
你好，这是为了在脱离本项目的情况下依然可以安装kubernetes官方文档使用kubeadm命令行而生成的
