### ISSUE TITLE
安装 kernel-ml 失败

### ISSUE THREAD

**Issue by 1455668754** [TimeBye/kubeadm-ha#78]
TASK [prepare/kernel : 安装 kernel-ml] ********************************************************************
fatal: [192.168.0.85]: FAILED! => {"changed": false, "msg": "Failure downloading http://files.saas.hand-china.com/kernel/centos/kernel-lt-5.4.92-1.el7.elrepo.x86_64.rpm, Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>"}
fatal: [192.168.0.229]: FAILED! => {"changed": false, "msg": "Failure downloading http://files.saas.hand-china.com/kernel/centos/kernel-lt-5.4.92-1.el7.elrepo.x86_64.rpm, Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>"}
fatal: [192.168.0.137]: FAILED! => {"changed": false, "msg": "Failure downloading http://files.saas.hand-china.com/kernel/centos/kernel-lt-5.4.92-1.el7.elrepo.x86_64.rpm, Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>"}

**Comment by TimeBye** [comment]
https://access.redhat.com/discussions/4487561
