### ISSUE TITLE
lb_kube_apiserver_port 不合理

### ISSUE THREAD

**Issue by zlingqu** [TimeBye/kubeadm-ha#8]
对于单master节点的集群，
roles\kube-master\certificates\tasks\kubeconfig.yml 中生成各个配置文件时，
--server=https://{{ KUBE_APISERVER_IP | trim }}:{{ lb_kube_apiserver_port | trim }} 段落，
使用lb_kube_apiserver_port 不合理，

建议修改roles\kube-master\certificates\defaults\main.yml中的lb_kube_apiserver_port配置，默认使用6443或者匹配host.ini中的另一个变量

**Comment by TimeBye** [comment]
你好，谢谢反馈，单节点也使用`lb_kube_apiserver_port`主要出于以下两个原因：
1. 因为使用同一个 network namespace 所以不会存在网络消耗问题
1. 便于后期集群从单节点扩展至多节点集群

故单节点中也使用了负载器
