### ISSUE TITLE
ingress-controller实例数量

### ISSUE THREAD

**Issue by longzhixin** [TimeBye/kubeadm-ha#80]
**缺陷描述**
请教下ingress-controller的实例部署问题
当前是每个work节点都部署了ingress-nginx-controller，是否需要每个节点都部署，还是只部署几个实例就可以，
```

[root@k8s# kubectl get pods -n ingress-controller | wc -l
91

```

**环境 (请填写以下信息):**

执行下面括号中的命令，提交返回结果

- **OS** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`): 
NAME="EulerOS"
VERSION="2.0 (SP5)"
ID="euleros"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP5)"
ANSI_COLOR="0;31"

- **Ansible版本** (`ansible --version`): 
ansible 2.9.21
- **Python版本** (`python --version`):
Python 2.7.5
- **Kubeadm-ha版本(commit)** (`git rev-parse --short HEAD`):

**Comment by TimeBye** [comment]
只部署几个实例就可以了，默认是每个worker节点都部署一个，你可以修改ingress-nginx-controller daemonset对象的nodeSelector为你想运行节点所包含的labels
