### ISSUE TITLE
离线部署ingress-nginx报错

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#81]
**缺陷描述**
![image](https://user-images.githubusercontent.com/33471335/143429961-d23a1d87-27f7-45a4-8a9a-e04d04f39f24.png)

离线部署ingress-nginx 报错
![image](https://user-images.githubusercontent.com/33471335/143430221-7f92815d-edb1-4df2-af99-fa185b8335b7.png)
ctr images pull 拉本地仓库这样不行？

**Comment by TimeBye** [comment]
1. 请查看一下etcd的运行情况


1. 请使用crictl命令行拉取
```
crictl pull registry.custom.local:12480/kubeadm-ha/nginx:1.19-alpine
```

**Comment by TimeBye** [comment]
![image](https://user-images.githubusercontent.com/22651579/143439166-214162d2-e7cf-4254-9d03-4045b05d2fd5.png)


经测试离线安装并没有问题
