### ISSUE TITLE
服务器原hostname设置不符合规范，部署失败

### ISSUE THREAD

**Issue by OscarLunch** [TimeBye/kubeadm-ha#86]
**缺陷描述**

这可能不能算是一个问题，获取算是一种现象。在之前部署过的项目中出现的一种情况

一开始服务器设置的hostname为：大写字符，下划线，但部署过程中总是出现异常。后修改为包含数字、小写字母、中划线类型的hostname才通过。建议考虑下这方面的设置，或做一个检测hostname设置异常的脚本，提示。

**环境 (请填写以下信息):**

执行下面括号中的命令，提交返回结果

- **OS** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`): redhat 7

- **Ansible版本** (`ansible --version`): 不太记得了

- **Python版本** (`python --version`): 不太记得了

- **Kubeadm-ha版本(commit)** (`git rev-parse --short HEAD`): 1.15.7

**Comment by TimeBye** [comment]
你好，该功能已在2020年1月1日添加，请使用本项目最新代码

653f10bfbcdd6d9b3026c493b1adf8176ba9a109
