### ISSUE TITLE
根证书续期规则不一致

### ISSUE THREAD

**Issue by zlingqu** [TimeBye/kubeadm-ha#9]
如下
pki/etcd/ca.csr
pki/ca.csr
不会自动续期

而pki/front-proxy-ca.crt会自动的续期

`
- name: 创建 etcd-ca 根证书
  shell: >
    openssl req -x509 -new -nodes -extensions v3_ca
    -subj "/CN=kubernetes"
    -config /etc/kubernetes/pki/etcd/etcd-openssl.cnf
    -key /etc/kubernetes/pki/etcd/ca.key
    -out /etc/kubernetes/pki/etcd/ca.crt
    -days {{ etcd_ca_certs_expired }}
  when: etcd_ca_crt_stat.stat.isreg is not defined

- name: 创建 kubernetes-ca 根证书
  shell: >
    openssl req -x509 -new -nodes
    -extensions v3_ca -subj "/CN=kubernetes"
    -config /etc/kubernetes/pki/kube-openssl.cnf
    -key /etc/kubernetes/pki/ca.key
    -out /etc/kubernetes/pki/ca.crt
    -days {{ kube_ca_certs_expired }}
  when: ca_crt_stat.stat.isreg is not defined

- name: 创建 front-proxy-ca 根证书
  shell: >
    openssl req -x509 -new -nodes
    -extensions v3_ca -subj "/CN=kubernetes"
    -config /etc/kubernetes/pki/kube-openssl.cnf
    -key /etc/kubernetes/pki/front-proxy-ca.key
    -out /etc/kubernetes/pki/front-proxy-ca.crt
    -days {{ kube_ca_certs_expired }}`

**Comment by TimeBye** [comment]
你好，谢谢反馈，这里 确实存在疏忽，我尽快将这里修复，谢谢
