### ISSUE TITLE
centos7.9升级内核到5.4.92后安装报错

### ISSUE THREAD

**Issue by tongsendong** [TimeBye/kubeadm-ha#95]
fatal: [192.168.0.182]: FAILED! => {"changed": false, "msg": "modprobe: FATAL: Module nf_conntrack_ipv4 not found.\n", "name": "nf_conntrack_ipv4", "params": "", "rc": 1, "state": "present", "stderr": "modprobe: FATAL: Module nf_conntrack_ipv4 not found.\n", "stderr_lines": ["modprobe: FATAL: Module nf_conntrack_ipv4 not found."], "stdout": "", "stdout_lines": []}

**Comment by TimeBye** [comment]
你好，这个是一个可忽略的报错，并不影响安装流程及集群使用
