### ISSUE TITLE
镜像仓库没有设置用户名和密码

### ISSUE THREAD

**Issue by EasonHe** [TimeBye/kubeadm-ha#97]
我在离线安装的时候，是私有镜像仓库但是，配置中没有发现设置用户名和密码，我只能手动去修改文件

**Comment by TimeBye** [comment]
你好，建议将安装集群所需的镜像放在公开仓库中哈，这部分镜像没必要设置在是有仓库中

**Comment by Taoup** [comment]
> 

registry.aliyuncs.com/kubeadm-ha

这个路径已经404了

**Comment by Taoup** [comment]
> 你好，建议将安装集群所需的镜像放在公开仓库中哈，这部分镜像没必要设置在是有仓库中

registry.aliyuncs.com/kubeadm-ha

这个路径好像已经404了

**Comment by TimeBye** [comment]
> 

请使用完整镜像地址进行 docker pull ，这个地址并不是使用浏览器进行访问的
